### ISSUE TITLE
Rapier is weird

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [darklordabc/chc2issues#10]
Apparently in solos rapiers can be picked up in duels (I rarely play solos so idk) but in duos it can only be picked up if dropped in your own arena if its dropped in the duel arena no one can pick it up. Rapier can also be put into stash unsure if intended.

**Comment by waylaidwanderer** [comment]
Nah rapier can't be picked up in solos either last time I tried, unless this was fixed in the last couple of days.

**Comment by fcalife** [comment]
should be fixed
