### ISSUE TITLE
[Suggestion] Give the underdog team/player (the team/player that has less money bet on them) a partial jackpot.

### ISSUE THREAD

**Issue by Draze22** [darklordabc/chc2issues#100]
At the moment you very rarely have no one bet on a team (because there is a huge potential gain for betting on the underdog) which makes jackpots almost impossible to get. 

My suggestion is that The team/player with less money bet on them gets a bigger jackpot the smaller the percentage bet on them. 50% bet on them would be regular dividends, 0% would be jackpot and the formula would scale linearly from one to the other. For example if a team were to have 25% of the money bet on them and win the duel they would be a payout exactly half way between the regular dividends and a jackpot.

This is the actual formula:

a = percent bet on a player
b = standard dividends 
c = standard jackpot
x = final payout (partial jackpot)

if a >= 50:
x = b

if 0 < a < 50:

x = b + ((c-b) x (50-a)/50)

if a = 0: 

x = c

This solution would keep the current betting system the same for the people betting but give the underdog team much more money for winning duels when other people bet very small amounts on them, which I see as the biggest problem with the current betting system.

**Comment by darklordabc** [comment]
Could this be fixed by making a minimum be amount? For example 10/5% of your total money is the lowest you can bet?

**Comment by Draze22** [comment]
Not really, could spend almost all your money, bet, then sell the item

**Comment by Draze22** [comment]
I've updated this suggestion to be clearer and have a standard mathematical formula.

**Comment by Draze22** [comment]
This will not be needed when the new betting system is implemented.
