### ISSUE TITLE
Fix random duel spawn positions

### ISSUE THREAD

**Issue by li0nza** [darklordabc/chc2issues#101]
When dueling, atleast in FFA, if you are listed 1st you should spawn left, and right if you are listed second.

**Comment by dym-sh** [comment]
maybe duel should have like 3~5 sec of "ready" time, so players can adopt to positioning and apply self-buffs?

**Comment by beepbeepboop** [comment]
@dym-sh That sounds risky, like you're asking for bugs to happen, people will find a way to take advantage of that "get ready" time. It would be better if they just allowed certain abilities to be self cast in fountain, the harmless ones like Empower

**Comment by mmdts** [comment]
Agree with fixed positioning.

**Completely disagree** with "get ready" time. Other than that being asking for bugs to happen, a big part of the duel was who gets to cast first. In perma-hex / perma-bash duels (usually countered by 3~4 satanics), a big part of winning is being able to get a jump on your enemy.

**Comment by dym-sh** [comment]
@mmdts counterpoint: perma bash/hex/aoe silence are simply imbalanced in duels, just as rearm+earth splitter imbalanced on creeps
and should not be tolerated

**Comment by mmdts** [comment]
> perma bash/hex/aoe silence are simply imbalanced in duels

Honestly, not sure if you've heard of status resist. Permanent bash is not permanent anymore when you've got satanics. I've won multiple games against people with focus fire + bash of the deep.

Bash of the deep and timelock in themselves are not broken. Bash and timelock are only insanely powerful with chemical rage (still counterable with dispersion / infernal blade + blink dagger). It's much easier to deal with than `refresher aghs crown multicast golems`, or `blink rearm hex` and even those are still counterable.

Aisde from some pretty bizarre 4~6 skill builds that you have to be very lucky to get, there aren't any spell combination in the entire game that are completely uncounterable by any other spell+item combination.

**Comment by dym-sh** [comment]
@mmdts 
> oh, its that ez! just get 5 satanics for duels!

on magic casters and summoners as well, ha, why didnt i think of that?

**Comment by Draze22** [comment]
@dym-sh you can also buy bkb for magic perma stun and halberd or ghost scepter for bash perma stun.

**Comment by dym-sh** [comment]
@Draze22
- all proc-[bashes](https://dota2.gamepedia.com/Bash) go through magic immunity
- there is a [Nullifier](https://dota2.gamepedia.com/Nullifier) against ethereal form and such

the only way is to win within the duration of [Shadow Realm](https://dota2.gamepedia.com/Dark_Willow#Shadow_Realm)

**Comment by Draze22** [comment]
Never said you bought bkb for bashes...
Can still use halberd to stop bashes...

**Comment by mmdts** [comment]
Or use Oracle's disarm...
If you also got good cooldown reduction, that's easily 100% disarm rate.

There's a lot of ways to counter them, I've beaten permabash with spirit bear, with vyse rearm, with all sorts of things. It all depends on the economy and who has more gold to play flexibly around the others.

**Comment by Sheodar** [comment]
Already added delay 3sec for duel start.
