### ISSUE TITLE
Late game round always give 2183 gold (possibly only duos)

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [darklordabc/chc2issues#105]
![image](https://user-images.githubusercontent.com/50186248/79045605-57788c00-7c4f-11ea-82f5-0765f7c261ec.png)
not sure if intended so ive marked as bug and balance, 2183 is consistent between 4 different games played.

**Comment by SanctusAnimus** [comment]
Round gold reward after 65th is constant `nRoundBaseBonus * math.pow(1.031, 65)`

**Comment by Draze22** [comment]
So a feature not a bug?

**Comment by SanctusAnimus** [comment]
yeah, that's intentional

**Comment by SanctusAnimus** [comment]
Closing since it's a feature
