### ISSUE TITLE
hero model loaded during round has fountain buff

### ISSUE THREAD

**Issue by dym-sh** [darklordabc/chc2issues#106]
steps to reproduce:

1. d/c at the initial pick phase
2. re-connecting _during_ round
3. (auto-)pick hero
4. new hero model can't be attacked, targeted, or interacted with in any way

had happened one time during first duel (had to restart entire PC due to perma-hang)

and here is someone who has auto-attacking disabled:

![20200411154050_1](https://user-images.githubusercontent.com/59403389/79045627-6427c080-7c0c-11ea-91ae-bbeba7e1e3c0.jpg)

**Comment by dym-sh** [comment]
rel: https://github.com/darklordabc/chc2issues/issues/65

**Comment by SanctusAnimus** [comment]
eh, creeps are supposed to remove this buff by their attacks, i'll see more into this issue

**Comment by AustraliaIsMyCity** [comment]
I've set it to urgent as it can be abused to prevent the game from continuing

**Comment by dym-sh** [comment]
related: 

1. player d/c at the start
2. player reconnects after the hero-pick expired
3. new hero model randoms
4. player instantly d/c + abandons
5. hero reverted to `io`
6. game never starts

![20200413165900_1](https://user-images.githubusercontent.com/59403389/79132369-7e97a080-7daa-11ea-89d4-9779a1ef810d.jpg)

**Comment by SanctusAnimus** [comment]
Should no longer be an issue
