### ISSUE TITLE
Fatal bonds lags the server a ton

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [darklordabc/chc2issues#107]
https://cdn.discordapp.com/attachments/694440472273354762/698528423148257310/2020-04-11_23-39-01.mov
Should it be removed/rewritten?

**Comment by SanctusAnimus** [comment]
Rewrite will probably yeild nothing, dealing this much damage instances in a single frame is just hard for dota to handle

**Comment by SanctusAnimus** [comment]
I've disabled it from multicasting for now, but i really don't want to remove this spell, it's cool

**Comment by SanctusAnimus** [comment]
Rewritten version should no longer cause lags that much at least.
