### ISSUE TITLE
upon being teleported back to the base the shop trigger takes 1-10 seconds to activate

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [darklordabc/chc2issues#11]

**Comment by darklordabc** [comment]
Yeah I dont undersatnd this one, its annoying

**Comment by AustraliaIsMyCity** [comment]
happens in normal dota with extremely high movement speed too

**Comment by SanctusAnimus** [comment]
This is dota triggers limit, and i don't know any way to force update it. They were reacting to teleportation like this from very beggining

**Comment by Draze22** [comment]
As far as I can tell the devs don't know how to fix this so I'm closing it for now.
