### ISSUE TITLE
Bedlam(/Frosthaven) + Phase Shift + Multicast

### ISSUE THREAD

**Issue by Blasphemy-Incarnate** [darklordabc/chc2issues#110]
Phase-shifting as you multicast bedlam(/frosthaven) causes the multicast's (that proc'd while shifted) will have their coords locked to wherever* you were at the time and will permanently** stay there.

E.g. If you get a 4x multicast and immediately phase shift, 3 bedlams will circle around that location* permanently (dealing damage).

*_If you move quickly afterwards there's a small frame where they will follow you before becoming stuck._
**_At least 10 minutes._

![image](https://user-images.githubusercontent.com/25470481/79047994-5189a780-7c5d-11ea-8c4e-8b0368dac8c1.png)

While not particularly insightful, there appears to be a max of ~8 bedlam's that can be stuck at a time. ~After that, they will just teleport to your location instead of creating new ones. Sometimes bedlam will teleport a bedlam frosthaven instead and vice versa.~ They actually just teleport to you when you use phase shift.

![image](https://user-images.githubusercontent.com/25470481/79048384-1a68c580-7c60-11ea-9aee-d3d4fdf5a23b.png)

**Comment by SanctusAnimus** [comment]
Fixed with next update
