### ISSUE TITLE
If you have 2 of the same ability and retrain you lose both

### ISSUE THREAD

**Issue by beepbeepboop** [darklordabc/chc2issues#111]
In duos mode if you have the same ability as your friend, then you swap something so that you now have a duplicate of the ability, then when you retrain you lose both and only get 1 ability back.

Common example:
This happens often to new players because friend1 is going magic build, friend2 is going right click.
Friend1 has lightning bolt already, friend2 gets offered lightning bolt and says "hey you wanna have 2 lightning bolts? that could be a lot of damage". They swap something and now friend1 has 2 of the same ability (duplicate versions of lightning bolt)
Friend1 then uses lightning bolt and finds out both abilities go on cooldown at the same time, is upset. "ah man this is useless I don't need both of these, I will retrain one of them" then when he retrains the lightningbolt both of the lightningbolts dissapear. And he only gets to choose one ability back. He now has 4 abilities instead of 5.

**Comment by SanctusAnimus** [comment]
**"2 lightning bolts"** will never work in dota, since they share cooldown, so idk why do you think it is a great idea to give your friend a second one. I'll probably just disable possibility to give duplicate ability via swap

**Comment by darklordabc** [comment]
Yeah two abilities is not going to work should be impossible to get two of the same ability

**Comment by beepbeepboop** [comment]
The first time I did it I thought "I wonder if I can have 2 of the same ability on separate cooldowns?"
I didn't know that they share a cooldown (most people don't know this until the test it)
So yes @SanctusAnimus it's much better if you just disable possibility to give duplicate ability via swap.
