### ISSUE TITLE
Walrus punch + bad juju aghanims 

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [darklordabc/chc2issues#114]
They should not work together as they infinitely loop and lag the server until the player runs out of mana (or crashes it if they have enough)

**Comment by mmdts** [comment]
Think this no longer loops infinitely (on anyone but tusk at least).
It still exhibits some strange behavior though depending on whether you cast another skill (with it on autocast) or specifically cast it.

**Comment by Draze22** [comment]
This is still a bug, a player named arzokh posted a video in bug report of this happening today.

**Comment by Draze22** [comment]
This not only crashes the server when essence flux is involved but it is also borderline broken in duels.

**Comment by SanctusAnimus** [comment]
Fixed in next update
