### ISSUE TITLE
Creep waves + general rebalance proposal

### ISSUE THREAD

**Issue by fcalife** [darklordabc/chc2issues#115]
Key points:
 * Creep rounds/waves will have a clearer separation between every group of 10 rounds, up to 50 (i.e. 1-10, 11-20, 21-30, etc.)
 * Every 10th round will be a special boss wave, a bit tougher than normal and with some special abilities. For every specific 10th round, there are 2 possible spawns (one is chosen randomly every game), with the exception of level 50, which is always Roshan.
 * There are no duels during boss rounds.
 * Boss rounds will be picked amongst the harder rounds currently in the game, such as the frostbitten one, or the one with two types of spiders.
 * Boss rounds will always drop neutral items, one per player in a team, corresponding to their round (tier 1 for round 10 boss, tier 2 for round 20 boss, etc.)
 * Conversely, neutral items are no longer dropped in random rounds
 * After each boss round, creeps' abilities go up one level, with a maximum level of 5. This means that creep abilities are going to be weaker early on, and stronger later (no more standing in the dragon fire and laughing about it).
 * Due to the above change, neutrals will no longer get bonus spell amp until after round 50.
 * After rounds 50, rounds will be fully random, with a boss round every 10 levels, also chosen randomly.
 * After round 50, creeps will start to scale in ways more significant than just damage & health. This will make the grind beyond lv50 way harder, and we hope people it will make people no longer have to grind out games for 3+ hours in order to get on the pve leaderboards.
 * With this change, we will also be adding new creep types, such as cleave creeps, evasion creeps, aura creeps, (actual) healer creeps...

---

Извините за автоматический перевод!

Ключевые моменты:
 * Раунды / волны ползучести будут иметь более четкое разделение между каждой группой из 10 раундов, вплоть до 50 (то есть 1-10, 11-20, 21-30 и т. Д.)
 * Каждый 10-й раунд будет особой волной босса, немного более жесткой, чем обычно, и с некоторыми особыми способностями. На каждый конкретный 10-й раунд есть 2 возможных появления (одно выбирается случайным образом в каждой игре), за исключением уровня 50, который всегда является Рошаном.
 * Во время раундов с боссами дуэлей нет.
 * Раунды боссов будут выбираться среди более сложных раундов в настоящее время в игре, таких как обмороженные или те, у которых есть два типа пауков.
 * В раундах боссов всегда выпадают нейтральные предметы, по одному на игрока в команде, соответствующие их раунду (уровень 1 для босса 10 раунда, уровень 2 для босса 20 раунда и т. Д.)
 * И наоборот, нейтральные предметы больше не выпадают в случайных раундах
 * После каждого раунда босса способности крипов поднимаются на один уровень с максимальным уровнем 5. Это означает, что способности крипов будут слабее в начале и сильнее в дальнейшем (больше не стоять в огне дракона и не смеяться над этим) ,
 * Из-за вышеуказанного изменения нейтральные игроки больше не будут получать бонусное усиление заклинания до окончания 50-го раунда.
 * После 50 раундов раунды будут полностью случайными, с боссовым раундом каждые 10 уровней, также выбираемым случайным образом.
 * После 50-го раунда крипы начнут масштабироваться более значительными способами, чем просто урон и здоровье. Это усложнит процесс преодоления 50 уровней, и мы надеемся, что людям больше не придется выкладывать игры более 3 часов, чтобы попасть в списки лидеров Pve.
 * С этим изменением мы также добавим новые типы крипов, такие как крипы крива, крипы уклонения, крипы ауры, (фактические) крипы целителя ...

**Comment by Draze22** [comment]
This has been implemented.
