### ISSUE TITLE
Sometimes after coming out of a duel you are unable to bet on the one immediately following it.

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [darklordabc/chc2issues#12]

**Comment by waylaidwanderer** [comment]
This happens all the time to me.

**Comment by Draze22** [comment]
Does this only happen when the duel ends after every other player/team completes the round?

**Comment by Draze22** [comment]
Has this been fixed with the new UI?

**Comment by Draze22** [comment]
Pretty sure this has been fixed.
