### ISSUE TITLE
Haunt teleportation issues

### ISSUE THREAD

**Issue by Blasphemy-Incarnate** [darklordabc/chc2issues#120]
Haunt allows players to teleport into other players arenas and damage  (#https://github.com/darklordabc/chc2issues/issues/73) them. It can then be used to stall the game. Haunt into someone else's arena and then stay there (until your teammate dies in the case of duos).
_Not sure if unobstructed pathing lets the neutrals get to you, but at least during the early rounds you can stall.

![image](https://user-images.githubusercontent.com/25470481/79072607-5023b200-7d25-11ea-8320-83bacfeb6d29.png)

Yet another reason haunt is a travesty.

**Comment by SanctusAnimus** [comment]
Haunt disabled from future update
