### ISSUE TITLE
Mortimer sceptre abuse

### ISSUE THREAD

**Issue by Blasphemy-Incarnate** [darklordabc/chc2issues#121]
You can shoot a creep or ally into someone else's arena, which can then be used to stall a game or disrupt it in some other way.

![image](https://user-images.githubusercontent.com/25470481/79073010-721e3400-7d27-11ea-8d8a-b515566737b0.png)

_Needs confirmation, image just shows the aftermath._

**Comment by SanctusAnimus** [comment]
cast range reduced from 3000 to 800 from next update
