### ISSUE TITLE
Tooltip MegaThread

### ISSUE THREAD

**Issue by beepbeepboop** [darklordabc/chc2issues#124]
(text for new players who don't know the intricacies and nuances that certain abilities have in custom games)
(also shows balances to abilities that make them different from how they act in normal dota)

Corrections/important-additions to tooltips here:

**Comment by beepbeepboop** [comment]
"aghanim not work" on Reincanation
"roshan is immune" on Earth Splitter

**Comment by beepbeepboop** [comment]
Add a tooltip to every ability that is blacklisted from Multicast
Add a tooltip to every ability that is blacklisted from Re-arm

**Comment by Draze22** [comment]
Add a tooltip to every ability that shows it's affected by spell amp but isn't
Add a tooltip to every ability that is affected by spell amp but shows that it's not.

**Comment by Draze22** [comment]
Will also need tooltips to describe exactly how each aghanim's upgrade that gives a new ability works (what abilities/hero are/is required to get the new ability).

**Comment by AustraliaIsMyCity** [comment]
This one thread is going to take someone like 200 hours to do like adding tooltips for **every** ability for rearm and multicast is not an easy or quick task

**Comment by darklordabc** [comment]
Maybe icons on abilities is a better idea like the recent charges change

**Comment by AustraliaIsMyCity** [comment]
something like this?
![multicast](https://user-images.githubusercontent.com/50186248/79093513-d11b9180-7d97-11ea-90ff-9807a879b78a.jpg)

**Comment by beepbeepboop** [comment]
I like these 2 options the most (regarding abilities that have been changed/balanced for this game mode):
Original:
![original](https://user-images.githubusercontent.com/35560562/79122033-007dce80-7d97-11ea-806a-f361196d393c.PNG)

A) add temporary writing to it
![renaimed](https://user-images.githubusercontent.com/35560562/79122055-0e335400-7d97-11ea-9dd9-96a93b1ef1fb.PNG)

B) Cut out out the scepter part so people know it doesn't work
![cropped](https://user-images.githubusercontent.com/35560562/79122061-14c1cb80-7d97-11ea-9f52-34f599046860.PNG)




When it comes to rearm and multicast I really like @AustraliaIsMyCity 's idea, 
For Re-arm you only have to change 16 icons, because there's only 16 abilties that are blacklisted from rearm
For multicast its only 3 as far as i know (Static link, chakram, rolling boulder)

So that's only roughly like 19 pictures to change

The spell amp on the other hand... that's gonna be a mission...

**Comment by AustraliaIsMyCity** [comment]
rearm is being redesigned and the multicast list is more like 50-100 long and growing

**Comment by Draze22** [comment]
This has been moved to the discord
