### ISSUE TITLE
Duel bet visibility to party members with the duelist

### ISSUE THREAD

**Issue by VIZE-X** [darklordabc/chc2issues#125]

**Comment by AustraliaIsMyCity** [comment]
Couldn't players just join the same lobby without being in a party though?

**Comment by Blasphemy-Incarnate** [comment]
The non-duelling members could also just tell their duelling friends that they bet on the opposing team and to throw.

**Comment by AustraliaIsMyCity** [comment]
This suggestion has an extreme flaw in that players could simply join the same lobby without being in a party to circumvent this
