### ISSUE TITLE
Add icon for abilities that don't work with multicast

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [darklordabc/chc2issues#127]
![image](https://user-images.githubusercontent.com/50186248/79097625-8f90e380-7da3-11ea-8944-6d402091def2.png)

**Comment by Draze22** [comment]
maybe add this to the tooltip megathread

**Comment by AustraliaIsMyCity** [comment]
not a tooltip tho

**Comment by Draze22** [comment]
It's instead of a tooltip to do the same thing as a tooltip for the same reasons though

**Comment by SanctusAnimus** [comment]
Implemented
