### ISSUE TITLE
Escaping arenas MegaThread (final 3 comments are relevant)

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [darklordabc/chc2issues#128]
Things with enough range that they allow you to leave or make other units leave arenas

**Comment by AustraliaIsMyCity** [comment]
Timberchain + timbersaw lvl 25 talent
Fallen sky [Tier 5 neutral item]

**Comment by dym-sh** [comment]
Tusk agh's Kick can place a creep outside (of the map?)
![20200412221427_1](https://user-images.githubusercontent.com/59403389/79131870-97538680-7da9-11ea-9556-6cb5d1e36323.jpg)

**Comment by SanctusAnimus** [comment]
kick distance is 500 now, how old is this screenshot?

**Comment by dym-sh** [comment]
@SanctusAnimus 12.apr.

**Comment by SanctusAnimus** [comment]
Allready fixed then

**Comment by AustraliaIsMyCity** [comment]
psionic trap aghs

**Comment by AustraliaIsMyCity** [comment]
illusiory orb especially with talent

**Comment by AustraliaIsMyCity** [comment]
multicast + movement abilities like fallen sky active

**Comment by AustraliaIsMyCity** [comment]
fallen sky plus cast range talent or aether lens lets you get into other arenas

**Comment by SanctusAnimus** [comment]
Everything from this list is fixed it seems, reopen if you stumble upon something new.

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/82324525-27c25e00-9a1d-11ea-91be-6f8eb699cb3d.png)
This means that you can escape arenas if on specific edges with many different abilities.

Can we please solve this by making the ffa map slightly bigger (more impassible terrain around the edge) rather than nerfing all cast ranges again. Alternatively we could remove aether lens and seer stone.

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/84092890-0eb93580-aa3c-11ea-96a3-f50229733e08.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/84231699-0e9b6180-ab32-11ea-8b6d-d14ba9ca1da2.png)

**Comment by Draze22** [comment]
This now has a permanent solution.
