### ISSUE TITLE
[Suggestion] Rework talents for abilities that have been removed.

### ISSUE THREAD

**Issue by Draze22** [darklordabc/chc2issues#132]
Give heroes with talents that affect abilities that are no longer in the game new ones.
Also a few talents in here that are useless or even detrimental with descriptions of why they're in this list.
Here's a possibly incomplete list with a suggestion for the new talent (didn't get very creative with the new talents):
Morphling right level 15 talent (+20s morph duration); +35 damage.

Storm Spirit left level 25 talent (500 distance auto remnant in ball lightning); +25% spell amp.

Io right level 25 talent (-30s relocate cooldown); +800 health.

Nature's Prophet right level 25 talent (removed teleportation cooldown); +40 intelligence.

Enchantress left level 20 talent (enchant affects ancients); +500 health.

Chen left level 15 talent (+20 holy persuasion damage); +12% spell amp.

Chen left level 20 talent (+1000 holy persuasion minimum health); +25% cooldown reduction.

Chen right level 25 talent (+5 holy persuasion max units); +40 intelligence.

Phoenix left level 20 talent (+1.25s supernova stun duration); +25 strength.

Phoenix right level 25 talent (+3 supernova hit count); +15 armor.

Rubick left level 25 talent (+50% spell amp for stolen spells); +30% cooldown reduction.

Disruptor right level 25 talent (-10s glimpse cooldown); +25% spell amp.

Skywrath Mage right level 20 talent (global concussive shot); +25 intelligence. Global skills don't do damage to heroes and stops concussive targeting the neutrals in your arena.

Shadow fiend left level 20 talent (+150 shadowraze damage); +25 agility.

Viper left level 25 talent (poison attack affects buildings); +40 agility. There are no buildings.

Doom left level 20 talent (devour can target ancients); +100 attack speed. Honestly don't know if this talent affects which creeps devour can target or not.

Undying right level 15 talent (+30 tombstone zombie damage); +15 strength.

Undying left level 20 talent ( +5 tombstone attacks to destroy); +10 armor.

Undying right level 20 talent (tombstone on death); +30% magic resistance.

Spectre right level 25 talent (+40% haunt illusion damage); +15 armor.

Nyx Assassin left level 25 talent (vendetta unobstructed pathing); +700 health. Feels like unobstructed pathing is mostly useless and borderline broken when it is useful.

Underlord left level 25 talent (25% firestorm building damage); +15 armor.

Visage right level 25 talent (+6 gravekeeper's cloak stacks); +40 intelligence.

Dark Willow left level 25 talent (+1.5s terrorize duration); +40 intelligence.

**Comment by Draze22** [comment]
Slardar left level 20 talent (+1000 night vision); +25 strength. Extra vision is useless.

Winter Wyvern left level 15 talent (+500 night vision); +12% spell amp. Extra vision is useless.

Spirit Breaker right level 10 talent (+600 night vision); +10 strength. Extra vision is useless.

Beastmaster left level 25 talent (-20s hawks cooldown); +25% spell amp. Hawks are useless.

Gyrocopter left level 25 talent (global cooldown); +40 agility. Global skills aren't (or at the very least shouldn't be) useful.

Lone Druid right level 15 talent (-12s savage roar cooldown); 15 agility. As far as I'm aware savage roar isn't in the game.

Monkey King right level 10 talent (+400 tree dance vision AoE); 20 damage.

Shadow Friend right level 15 talent (presence aura affects buildings); +30 damage.

Treant Protector left level 10 talent (nature's guise invisibility); +5 armor.

**Comment by AustraliaIsMyCity** [comment]
done
