### ISSUE TITLE
Offers / Bugs

### ISSUE THREAD

**Issue by Wintarogar** [darklordabc/chc2issues#137]
I don’t know how much this is realized, but I like this game and I would like to participate in improving it.
### Duet mode:
If in two pairs the player finally left the game, make it possible to reassemble the party with another solo player. Suppose - an item in the store sending such a request to another lone player.
When choosing a hero, add the desired role on the right - let's say Melee (tank, Kerry) Ranged battle (Kerry), Mage / Summoner. Or add an item that makes the main stat change, and, accordingly, all bonuses. For example, intelligence in agility, etc. With an increase in price from the beginning of the game.
Or add the ability to re-select a hero from 3 new ones within 5 minutes of the game.
For if you enter the game outside the party, you can get 2 mages or 2 melee, which is almost hardcore.
The ability to transfer gold to teammate.
### Solo mode:
It is almost impossible to reach the top 1 with a purely magical assembly. Damage is not enough, you die from creeps from a blow. Also, for a magician, there are no power-ups in PvE except one item. Even having gold has nothing to strengthen abilities. Suggestion - add an item that increases the damage from abilities as a percentage of the health of creeps, only
Add damage triggering for aeon disk from creep damage.
Increase the chance of falling neutral items, especially for solo games
In general, this custom is already an order of magnitude better than the old one, develop further
### Seen bugs:
Greater bash spirit breakera can push Roshan into the corner of the map, from where he cannot get out.
Character ir Spirits does not work with aghanims scepter, the ability becomes inactive and does not work.
Techies - his mines remain in the arena, due to which you can make a kill while standing at the fountain
Also, I ask you to pay attention to the talents of the heroes for the missing abilities. To give the opportunity to replace them with at least a bonus to the characteristics, etc.

**Comment by Draze22** [comment]
Not sure what the first duos (duet) suggestion is. Duos is primarily designed to be played by 2 people who are in a discord together not by yourself with a random person, if you are by yourself you can play ffa. There may be changes made to make it so duos is better for playing with strangers but for now its not a priority.

Specific magic damage spells/combos like midnight pulse, infernal blade, earthsplitter, rearm +arrow/devour, etc are extremely good at getting first place it just takes some practice to know how to make these sorts of spells work well. Each point of intelligence gives you 0.6% spell amp during creep rounds and 0.2% during duels so buying lots of intelligence lets you get stronger as the game goes on if you are playing a caster build. This spell amp does not currently display while in the fountain but if you check during the round you will see it.

As far as surviving getting hit by creeps as a caster all you have to do is buy an octarine core (so your spell damage heals you), multiple shiva's guards to give you armour (take less damage), the option of a heart if your spell damage is lower but you have good defensive abilities. You can also buy a ghost scepter to make you physically immune for 4 seconds.

The aeon disk suggestion could be a good one in the future, I'll add it to a bigger group of suggestions.

Neutral item drop rates are going to be improved soon as far as I know.

The ability to transfer gold to your team mate will likely never be implemented however you can buy retrain books for you team mate to help them out.

Paying gold to change your main stat is an interesting idea, however it would be very difficult for the developers to add to the game so it might be a long time before it gets considered.

The bugs you mentioned are ones we know about and I already have a list of all the talents that are not useful.

Thank you for your feedback and I hope I was able to give you a better idea of how to do well in this challenging game.

**Comment by Wintarogar** [comment]
With each update, getting better, basically. Apart from, of course, constant bugs and fixes)). And yet I would like to draw attention to the choice of a hero in duet mode. Often I play outside the party, and if you both picked a mage or a tank, you have very little chance of surviving to round 50. Because of this, when choosing a hero, I wanted to see what your partner chooses. The same question, and not too much affect the balance of these 2 new reroll for real money?

**Comment by darklordabc** [comment]
We plan to let you see which hero your partner is thinking of picking and adding a confirm button to duo so you can coordinate.

**Comment by Wintarogar** [comment]
also faced with a negative attitude towards the game. A person comes in, chooses a hero, maybe takes a couple of skills - and just leaves the game. It is possible to make a penalty for leaving before one’s death, at least.

**Comment by Wintarogar** [comment]
I would like to improve the summoners, namely, an object that blocks the ability to randomly change a book

**Comment by Wintarogar** [comment]
Error - Ultimate drow ranger marksmanship does not work on a number of heroes. (slark, axe ) . Although everything worked in ability, it would not be bad to remove the restriction on disabling the ultimate if there was an enemy nearby

**Comment by Draze22** [comment]
That's not an error, that's just how the ability works.

**Comment by Wintarogar** [comment]
> Это не ошибка, это просто так работает способность.

But ability draft  works quietly? I also wanted 1 complete impiety after death from creeps, because you can’t even have time to activate an object or ability

**Comment by Wintarogar** [comment]
Add the ability to completely control the partner who left the game - exchange skills, sell his items, etc.

**Comment by Wintarogar** [comment]
Upgrade heroes with a stat of strength. At the moment, no matter how much health you have, you will still die in a couple of seconds from creeps in high rounds. Suggestion: Add a bonus for such heroes to fight with creeps - for every 100 strength - ignore 10% of damage received and 1% of damage reflection

**Comment by Draze22** [comment]
@Wintarogar can you take any suggestions from here and put them in separate github entries so they can be individually discussed more easily.
