### ISSUE TITLE
Reincarnation in duels sometimes lets the duel end while a player is still reincarnating

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [darklordabc/chc2issues#14]
Not sure what happens in solo but in duos its very common to bug out and do this

**Comment by Draze22** [comment]
This happens when the the player with reincarnation is reincarnating while their team mate dies.

**Comment by Draze22** [comment]
Can also do some weird things in creep rounds.

![image](https://user-images.githubusercontent.com/63279022/81644019-45665500-946a-11ea-818f-7243ea75c48d.png)

**Comment by Sheodar** [comment]
Fixed
