### ISSUE TITLE
Bad Juju + Octarine + Drow/SF CDR

### ISSUE THREAD

**Issue by mmdts** [darklordabc/chc2issues#143]
Bad Juju + Octarine + Drow/SF CDR, when combined, allow for permanent grave or shadow realm or tricks of the trade.

**Comment by SanctusAnimus** [comment]
SF/Drow can't have bad juju, it's a hardcoded limitation. Did you swap them in duos or what

**Comment by mmdts** [comment]
Oh, nevermind then, I got it in ability draft when testing spell combinations, and assumed it'd be there in CHC, which is bad on my part.
![image](https://user-images.githubusercontent.com/14915907/80279983-3d37b700-8701-11ea-8c82-a45052db841f.png)


There should be a note for that hard-coded limitation though. Is it just drow + SF, or is tide included as well?

Riki bad juju with the cdr tree still tricks permanently, doesn't he?
