### ISSUE TITLE
Multicast + Tricks of the Trade leaves shadow copies of you

### ISSUE THREAD

**Issue by mmdts** [darklordabc/chc2issues#144]
![image](https://user-images.githubusercontent.com/14915907/80279763-d960be80-86ff-11ea-88ab-9d20b66f6bfb.png)
Shadow copies that are left cause the stun creeps and break creeps to stun/break in the middle of nowhere.

Also, I believe this could take you out of the arena on a 4x multicast

**Comment by SanctusAnimus** [comment]
Tricks of the trade are not multicastable already.
