### ISSUE TITLE
Take aim doesn't give melee heroes extra range.

### ISSUE THREAD

**Issue by Draze22** [darklordabc/chc2issues#146]
Take aim doesn't give melee heroes the +400 range despite it working on melee heroes in ability draft. If this is intended I will add a tooltip to tell people if not then its a bug.

**Comment by darklordabc** [comment]
Added a ability note to takeaim saying it doesnt work on melee

**Comment by Draze22** [comment]
Is this getting changed at some point are is it being left as a melee only ability?
