### ISSUE TITLE
Artic burn gives infinite attack range under rare circumstances.

### ISSUE THREAD

**Issue by Draze22** [darklordabc/chc2issues#147]
This is from a guy messing around with cheats but I've also seen a screenshot from someone who had it happen in a regular game. Neither new why it happened.
![image](https://user-images.githubusercontent.com/63279022/80283644-88cb7e80-875c-11ea-820f-d7b7b91ef32a.png)

**Comment by mmdts** [comment]
Can confirm. Someone had infinite attack range (10K+) on arctic burn + split shot, and then his attack range got fixed out of nowhere (to ~1000)

**Comment by Draze22** [comment]
Seems to be a visual bug and doesn't actually give you abnormal attack range.

**Comment by SanctusAnimus** [comment]
Visual bug, shouldn't influence anything
