### ISSUE TITLE
Abilites with charges act weirdly with cooldown reduction and fountain cooldown speedup

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [darklordabc/chc2issues#15]
Also abilities like sleight of fist where they have a talent rely on charges act weirdly too even before the talent is upgraded (or even if they aren't on the hero with the talent)

**Comment by SanctusAnimus** [comment]
Wdym weirdly

**Comment by AustraliaIsMyCity** [comment]
> Wdym weirdly

they arent effected by the cooldown reduction

**Comment by Draze22** [comment]
Ok I tested this and abilities with charges are affected by cooldown reduction only if they have 0 charges remaining.

**Comment by SanctusAnimus** [comment]
FIxed totally, yet duration of modifier indicator doesn't update properly, blame Valve for the great synchronization
