### ISSUE TITLE
Rounds are sometimes countinuing after everyone dies

### ISSUE THREAD

**Issue by Draze22** [darklordabc/chc2issues#150]
Several people have reported rounds continuing after everyone dies.
![image](https://user-images.githubusercontent.com/63279022/80394576-615be980-88f5-11ea-97d1-987cc2765bf5.png)

Interestingly mmdts also reported that aegises were not being lost in when there were less than 5 players remaining in the game and that when everyone ended up losing the game continued on.

Looks like at least 1 developer is aware of this but I thought I would open an issue on it anyway.

**Comment by mmdts** [comment]
I think this got fixed? Someone confirm and close.
