### ISSUE TITLE
game needs a separate testing facility for future updates

### ISSUE THREAD

**Issue by dym-sh** [darklordabc/chc2issues#153]
currently game is in every way unplayable, since server just does not loads
its second time this week as well

a separate mod for testing future updates, instead of just pushing to production would be a welcome workflow change

**Comment by dym-sh** [comment]
honestly
![20200504014325_1](https://user-images.githubusercontent.com/59403389/80928982-d2454a80-8da8-11ea-93a2-509b2401426b.jpg)

**Comment by dym-sh** [comment]
the bigger problem tho – mod will NOT be auto-updated until full dota restart

**Comment by Draze22** [comment]
We essentially just got this when Sanctus Animus shared some cheat commands to test things in CHC.
