### ISSUE TITLE
[breaking] player reconnecting inbetween rounds (after he d/c during hero pick) will stop the game timer

### ISSUE THREAD

**Issue by dym-sh** [darklordabc/chc2issues#154]
steps:

1. player d/c at the start  (before the hero-pick expired)
2. player reconnects inbetween rounds
3. random hero model loads
4. game timer just stops

happens in like every 4th game in duos

![20200430175254_1](https://user-images.githubusercontent.com/59403389/80732610-dc4b1d00-8b0c-11ea-9cad-7c0178656502.jpg)

**Comment by dym-sh** [comment]
i would suggest loading random hero model for everyone the moment hero-pick expired

this will also fix the #65

**Comment by SanctusAnimus** [comment]
we can't force pick a hero for disconnected player, it's DOTA limitation

**Comment by SanctusAnimus** [comment]
And #65 is already fixed

**Comment by dym-sh** [comment]
i have not encountered this bug in a while, but im not sure it's acly gone

**Comment by Draze22** [comment]
Closing this until we have another occurrence of this bug.
