### ISSUE TITLE
Punishment for leaving the game prematurely

### ISSUE THREAD

**Issue by Wintarogar** [darklordabc/chc2issues#157]
In view of the frequent, almost every 3 game, leaving the game by random allies, I suggest:
Add punishment for premature showers (ban for an hour in the library, etc.)
Do not take into account the rating if a random ally completely showered in the first 30 minutes.
Either compensate for the lack of an ally with a double bonus on gold or a buff on characteristics / revival.
The game of solo in the absence of gold turns into sadomasochism with an attempt not to drop the rating.
Thank you for improving the game.

**Comment by mmdts** [comment]
> [5:51 PM] darklord: Game is too casual for leaver peanlty

penalty*
Think that warrants this for closing, but going to leave it to someone else with more authority to close.

**Comment by darklordabc** [comment]
Yes we won't be adding leaver penalty for this game, but thanks for the feedback anyway.
