### ISSUE TITLE
Suggestion/bug: Stop innate abilities from being able to be retrained and from being swappable in duos

### ISSUE THREAD

**Issue by Draze22** [darklordabc/chc2issues#160]
Not sure if being able to swap innate abilities with your duos partner and being able able to retrain the innate abilities is intended, if it isn't then its a bug and needs to be fixed ASAP. If it is intended then I would highly recommend changing both of these features. 

Being able to retrain them allows you to have 7 abilities on 1 hero which changes the balance of the game, makes innates feel more like an extra skill and defeats the whole idea of them being 'innate'.

Being able to swap them in duos currently allows one player to have both innate abilities which unbalances them as they are balanced around only being able to have one of them. It also does weird things like allowing you to unskill the innate abilities and put the skill points into other skills.

**Comment by Wintarogar** [comment]
At a minimum, I ask you to make it possible to change innate abilities to other innate abilities in a book.
