### ISSUE TITLE
People getting attacked in fountain

### ISSUE THREAD

**Issue by Draze22** [darklordabc/chc2issues#169]
Multiple people have complained that they have been attacked in fountain for extended periods of time, died and lost aegises.
![image](https://user-images.githubusercontent.com/63279022/81283200-990a2480-909f-11ea-9fe2-34d40e6e039f.png)

**Comment by Draze22** [comment]
Had this happen to me in a game. It was only before the first round started, I managed to not die and when I got back to the fountain everything was normal. I had the issue where you disconnect while picking and when you reconnect you can see the ability pick screen and the hero pick screen at the same time. It seemed like the two events were linked.

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/83481651-b6d17a80-a4e1-11ea-94b9-bbd7137de799.png)

**Comment by SanctusAnimus** [comment]
Is this still an issue?

**Comment by Draze22** [comment]
Pretty sure SanctusAnimus is correct and this is no longer an issue.
