### ISSUE TITLE
If you don't choose an innate ability you lose the option of choosing abilities forever.

### ISSUE THREAD

**Issue by Draze22** [darklordabc/chc2issues#173]
If you don't choose an innate ability after approximately 5 rounds you lose the option of choosing an innate ability ever and can not choose regular abilities either.

The specifics need confirmation but at the very least a bug similar to this exists.

**Comment by fcalife** [comment]
Should fix this together with the addition of the 'choose later' option

**Comment by fcalife** [comment]
Fixed by sheodar yesterday I believe
