### ISSUE TITLE
Force boots bug.

### ISSUE THREAD

**Issue by Draze22** [darklordabc/chc2issues#174]
I had... aghs. on arctic burn. i was just playing around the small hole so the creeps go around when i move to the other side then i go back so they cant hit me. but force boots just forced boots me again. after i used it 5 secs before it forced boots me back again. but towards the creep. so i died. (Robby_)

Not sure if this is a bug or if the player who reported it just missclicked arctic burn.

**Comment by fcalife** [comment]
Assuming the player didn't misreport, what would the bug here be?

**Comment by Draze22** [comment]
From what I can tell it would be a bug with force boots activating while on cooldown.

**Comment by fcalife** [comment]
Think we can close this honestly, bit too vague and if its a bug with an actual unchanged neutral item, it's a dota thing.
