### ISSUE TITLE
Integer overflow bug from borrowed time + round 969 enemy.

### ISSUE THREAD

**Issue by Draze22** [darklordabc/chc2issues#175]
The bug caused the player to get stuck at 1 hp after getting hit by a round 969 Roshan with borrowed time active. Seems like it could be integer overflow from technically healing over the integer limit with borrowed time.
https://clips.twitch.tv/TangentialTentativeWoodcockMau5

**Comment by dym-sh** [comment]
happened way before with possible addition of false promise in the mix:

![20200506140015_1](https://user-images.githubusercontent.com/59403389/81350327-f9aa5900-90c1-11ea-8f8d-cce7cf9eff15.jpg)

**Comment by fcalife** [comment]
No need to fix this now due to numbers being less inflated after the creep rework arrives.
