### ISSUE TITLE
Change where the move abilities and swap abilities buttons are.

### ISSUE THREAD

**Issue by Draze22** [darklordabc/chc2issues#178]
Currently the abilities order and swap abilities (duos) hotkeys are unusable when you have unused skill points and could use them to upgrade a talent.

![image](https://user-images.githubusercontent.com/63279022/81398444-90cbeb00-916c-11ea-8012-5b25e87f33f0.png)
![image](https://user-images.githubusercontent.com/63279022/81398511-a6411500-916c-11ea-9101-2ac73539be99.png)

This is rarely an issue but sometimes forces you to upgrade a talent instead of saving a skill point to upgrade an ultimate because you have 5 of them.

Could also just add these buttons back to the top left corner for people in these sorts of situations.

**Comment by SanctusAnimus** [comment]
Should be fixed
