### ISSUE TITLE
Broken wild axes cooldown (probably caused by multicast).

### ISSUE THREAD

**Issue by Draze22** [darklordabc/chc2issues#188]
![image](https://user-images.githubusercontent.com/63279022/81491484-74e25980-92d2-11ea-8606-574bdc79aac7.png)

Not sure if this a bug or if this is just a screenshot taken while the axes are off screen somewhere or something like that.

**Comment by mmdts** [comment]
He just won a duel as you can see. Axes probably haven't returned from the duel arena yet.

**Comment by Draze22** [comment]
Yeah its probably that but I wanted to have this here just in case it is a bug.

**Comment by Draze22** [comment]
looks like the bug is caused by multicasting wild axes, possibly at the end of a round as the creeps are dying.

![image](https://user-images.githubusercontent.com/63279022/82729330-05408580-9d3a-11ea-880c-15871c9d1a12.png)

**Comment by Draze22** [comment]
Seems like this bug can be caused by the player dying while wild axes is being multicast.

![image](https://user-images.githubusercontent.com/63279022/83481099-44ac6600-a4e0-11ea-9903-6ed5a2e730c8.png)

**Comment by Draze22** [comment]
Wild axes has been disabled from multicasting and this bug therefor cannot occur.
