### ISSUE TITLE
Rounds keep going on if a player DC's at start, gives wrong placement too

### ISSUE THREAD

**Issue by mmdts** [darklordabc/chc2issues#193]
Pink DC'ed at the very start before hero picks and before he gets turned into IO.

I won, tells me I'm rank 2/10... Rounds keep going on even though no one is alive.
I died on round 57, it's now round 130ish.

![image](https://user-images.githubusercontent.com/14915907/81497103-87519880-92bc-11ea-9072-0e446c626b2c.png)

**Comment by Draze22** [comment]
Another example of this happening

![image](https://user-images.githubusercontent.com/63279022/81532958-a9c0e000-93a8-11ea-9984-cb0976fd570b.png)

**Comment by Draze22** [comment]
Another example.

![image](https://user-images.githubusercontent.com/63279022/81787248-1ae8ca80-9544-11ea-9181-9da1c74b76ab.png)

**Comment by Draze22** [comment]
Yet another example of this bug occuring.

![image](https://user-images.githubusercontent.com/63279022/81910585-7d5acd00-960f-11ea-9215-7004adc0459c.png)

**Comment by Draze22** [comment]
Another one.

![image](https://user-images.githubusercontent.com/63279022/82009498-d3348100-96b2-11ea-8df3-7e9b81db3948.png)

**Comment by Draze22** [comment]
When this bug occurs the dc'd player has 999 kills and deaths for some reason.

![image](https://user-images.githubusercontent.com/63279022/82137340-6cea6280-985a-11ea-9b1f-08a41b2c8913.png)

**Comment by Al-Khedhir** [comment]
@mmdts hello my friend. is there a way of contacting you?

thanks

**Comment by Draze22** [comment]
Pretty sure this got fixed.
