### ISSUE TITLE
The patch of impassible terrain in ffa is easily abusable.

### ISSUE THREAD

**Issue by Draze22** [darklordabc/chc2issues#196]
Not necessary to remove this section of the map but people can easily stay in this area with flying movement and as you can see in the image below wait out the timer and troll people.

Players are growing quite impatient with the number of trolls and the ease with which they can waste the other players time. Waiting 200 extra seconds most rounds for ~50 rounds often wastes an extra hour of player's time.

The parts of the map that are easy to abuse like this one either need to be systematically removed or the 200 seconds of overtime players get needs to be shortened and at least remove one of the players aegises once it ends. (The second option would be a better long term solution that would lessen all abuse of this kind). 

![image](https://user-images.githubusercontent.com/63279022/81500567-5736e380-9316-11ea-9a5d-378ddcf850c2.png)

**Comment by fcalife** [comment]
The patch of unpathable terrain has been removed in the 2.0 branch
