### ISSUE TITLE
tornado doesnt display cooldown

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/chc2issues#2]
![image](https://user-images.githubusercontent.com/16277198/78449943-aa3dcb00-76c6-11ea-995f-f770e0a907c7.png)

**Comment by fcalife** [comment]
fixed next update/upload

**Comment by darklordabc** [comment]
![image](https://user-images.githubusercontent.com/16277198/79034302-4c464180-7bf8-11ea-8402-b07a8f8d4fb8.png)
Fixed
