### ISSUE TITLE
Torrent storm can last abnormally long when multicast.

### ISSUE THREAD

**Issue by Draze22** [darklordabc/chc2issues#200]
This bug seems similar to the bugs that were happening with abilities like bedlam and chakram a while ago. Probably just needs to be added to the multicast ban list.

![image](https://user-images.githubusercontent.com/63279022/81534991-551f6400-93ac-11ea-9d2f-1d83b314160c.png)

**Comment by fcalife** [comment]
Couldn't replicate this even with massive spam of torrent, torrent storm, and both bedlams. Some other factor must be involved.

**Comment by Draze22** [comment]
I found the same thing when testing it, closing this for now until someone else reports this bug (if they ever do). Seems like the person who reported it just saw a lot of spells flying around but didn't realize ogre was rearming torrent storm or had bad juju or something like that.
