### ISSUE TITLE
Casting bloodrage in fountain does nothing and puts it on cd.

### ISSUE THREAD

**Issue by Draze22** [darklordabc/chc2issues#201]
![image](https://user-images.githubusercontent.com/63279022/81638886-b2272280-945d-11ea-8473-fe03485d331c.png)

Can confirm this is true.

**Comment by SanctusAnimus** [comment]
Seems right, but reasons are unknown, so i'll leave it delayed for now

**Comment by SanctusAnimus** [comment]
Fixed by gaben
