### ISSUE TITLE
Psionic trap aghanim's ability (psionic projection) can be retrained.

### ISSUE THREAD

**Issue by Draze22** [darklordabc/chc2issues#202]
![image](https://user-images.githubusercontent.com/63279022/81639152-79d41400-945e-11ea-80b4-74471a6db22b.png)

![image](https://user-images.githubusercontent.com/63279022/81638959-ee5a8300-945d-11ea-8df4-77c53041dba1.png)

This is obviously a huge problem as it can be abused easily.

**Comment by fcalife** [comment]
Made the ability unremovable
