### ISSUE TITLE
Scoreboard sometimes doesn't show mmr changes

### ISSUE THREAD

**Issue by mmdts** [darklordabc/chc2issues#208]
![image](https://user-images.githubusercontent.com/14915907/81898839-c3854180-95b9-11ea-9a67-342264a3028a.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/81911098-2a354a00-9610-11ea-8b83-4cab1384bf86.png)
![image](https://user-images.githubusercontent.com/63279022/81911074-243f6900-9610-11ea-9d1e-2b45b3842392.png)

**Comment by Draze22** [comment]
This isn't a bug, people have just been starting partially filled lobbies thinking they count towards mmr.
