### ISSUE TITLE
Searing arrows multishot + marksmanship aghs + equilibrium causes an attack loop.

### ISSUE THREAD

**Issue by Draze22** [darklordabc/chc2issues#209]
Searing arrows multishot + marksmanship aghs + equilibrium causes an ever increasing number of attacks until either all the creeps die or the server crashes. Some of these abilities (and maybe clinkz himself) need to not be able to be rolled together.

![image](https://user-images.githubusercontent.com/63279022/81903345-00c2f100-9605-11ea-85f9-9e2aa7be9a1a.png)

**Comment by SanctusAnimus** [comment]
Fixed in next update
