### ISSUE TITLE
Roshan (and creeps) sometimes walk/s to fountain (sit in a corner in the current patch) because their ai breaks.

### ISSUE THREAD

**Issue by Draze22** [darklordabc/chc2issues#210]
Update: this bug can be caused by any ability that stops Roshan from being able to target the player most commonly (possibly only) after the creeps/Roshan gain/s flying movement.

![image](https://user-images.githubusercontent.com/63279022/81909498-096bf500-960e-11ea-978a-f6aa8ac49e5f.png)

The other players killed Rosh and the game continued on normally afaik.

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/81910766-b4c97980-960f-11ea-9b77-d3e0adfb0eaa.png)

**Comment by Draze22** [comment]
Regular creeps also do it sometimes.

![image](https://user-images.githubusercontent.com/63279022/82009144-e1ce6880-96b1-11ea-9e1b-bee976165d2c.png)

**Comment by Draze22** [comment]
Pretty sure smoke of deceit is causing this bug in most if not all cases, hence why its mostly happening on rosh round but can happen on other rounds.

**Comment by dym-sh** [comment]
![20200523001408_1](https://user-images.githubusercontent.com/59403389/82715612-3bc3c500-9c94-11ea-875a-102efa41dbaf.jpg)

**Comment by SanctusAnimus** [comment]
Creeps no longer have flight (but bonus attack range), should no longer be an issue

**Comment by Draze22** [comment]
This issue has now just reverted to the old issue where the creep ai breaks and they stand in a corner until killed or the timer runs out.

**Comment by SanctusAnimus** [comment]
They will gain enough attack range eventually and it shouldn't be an issue after creep rework. If anything, it should be a separate issue about AI, renaming same one doesn't help much tbh

**Comment by Draze22** [comment]
Feel free to open a new issue that you think makes more sense then.
