### ISSUE TITLE
灰烬之灵四技能,进入怪物房时候释放有bug  Ember Spirit‘s four skill have a bug

### ISSUE THREAD

**Issue by oooops** [darklordabc/chc2issues#211]
在倒数完毕准备进入怪物房的时候,释放火猫四技能不会进入区域,并且能够被其他玩家攻击
when the time end,at the last one second,use Ember Spirit‘s four skill,I can not enter the monster's area and can be attacked by other players

**Comment by Draze22** [comment]
In other words fire remnant can be used to stay in the fountain when the creep round or a duel starts.
This needs fixing ASAP.

**Comment by Draze22** [comment]
This should be less abusable next update.

**Comment by SanctusAnimus** [comment]
Fire remnants are no longer castable on base, should no longer be an issue
