### ISSUE TITLE
neutral items can drop outside the arena.

### ISSUE THREAD

**Issue by Draze22** [darklordabc/chc2issues#212]
If a neutral item drops outside the arena it can only be picked up using a movement ability such as burrowstrike or pounce.

![image](https://user-images.githubusercontent.com/63279022/81952705-28887800-964a-11ea-8ed7-3ece6bdfa826.png)
![image](https://user-images.githubusercontent.com/63279022/81952865-540b6280-964a-11ea-825c-a49f7985e06d.png)
![image](https://user-images.githubusercontent.com/63279022/81952887-5a014380-964a-11ea-9012-12e43d51d883.png)

**Comment by SanctusAnimus** [comment]
With newcoming neutral item drop algo will not be an issue, closing
