### ISSUE TITLE
Starstorm aghs doesn't work properly.

### ISSUE THREAD

**Issue by Draze22** [darklordabc/chc2issues#221]
![image](https://user-images.githubusercontent.com/63279022/82239902-da8eaf80-997c-11ea-9745-089ae9f49cca.png)
![image](https://user-images.githubusercontent.com/63279022/82239966-f4c88d80-997c-11ea-8e69-b67ccafe92eb.png)

**Comment by dym-sh** [comment]
yes, can confirm, early aghs fucks over starstorm – it looks like it triggers 10 times on fist occasion, and then nothing

and yes, first death (in duel) restores passive procs every 8 sec

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/82746210-a5e18480-9dd0-11ea-832d-fccb08c549fb.png)

**Comment by SanctusAnimus** [comment]
Should be fixed
