### ISSUE TITLE
Torn page can retrain abilities that cannot be retrained.

### ISSUE THREAD

**Issue by Draze22** [darklordabc/chc2issues#224]
This means that if you get lucky/unlucky you can cause all the bugs associated with retraining spirits, chackram, astral spirit, etc.

**Comment by darklordabc** [comment]
I just tested this, with chakram and I couldnt retrain the ability after trying many times, is this still currnt?

**Comment by Draze22** [comment]
Don't know.

**Comment by Draze22** [comment]
You are correct, this is no longer the case.
