### ISSUE TITLE
Disconnecting during the hero picking phase can cause the player to be unable to control their hero

### ISSUE THREAD

**Issue by Draze22** [darklordabc/chc2issues#228]
I disconnected during the picking phase and it took me 6 rounds to reconnect. Once I finally did I could only partially control my hero. I could upgrade talents but not abilities, I could swap abilities with my partner but they couldn't swap them with me, I could move items around in my inventory but couldn't drop them or use them. I could bet money on duels but couldn't spend any money. Finally I couldn't move my hero around, use abilities or force my hero to attack.

Whatever system is currently in place for spawning in heroes is super weird. It either needs to be fixed or the hero pick screen needs to not be super cpu intensive and cause people to dc.

**Comment by dym-sh** [comment]
it might help to start a private lobby with the intended map, before acly playing. loading three hero models at the start is not a "big load", but i had some problems from the fact that they all load at the same time, thread-blocking each other or smth

**Comment by Draze22** [comment]
Doing that does help, I just forget sometimes and have this sort of stuff happen.

**Comment by Draze22** [comment]
Another player experiencing the same thing with similar prior circumstances. Looks like disconnecting before being assigned a hero is what causes this bug to occur.

![image](https://user-images.githubusercontent.com/63279022/83506914-20b24a00-a50b-11ea-86a7-1c39f74ed97f.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/84586809-c34cc000-ae5d-11ea-82b4-73d97a07215d.png)
![image](https://user-images.githubusercontent.com/63279022/84586816-cd6ebe80-ae5d-11ea-9b2b-3653277f4638.png)

**Comment by dym-sh** [comment]
still relevant

**Comment by Sheodar** [comment]
Should be fixed. I tested it in duos. I can move/buy items/use and upgrade skills/etc.
