### ISSUE TITLE
Swapping Lone Druid's True Form only transmits one skill

### ISSUE THREAD

**Issue by dym-sh** [darklordabc/chc2issues#229]
![20200523154933_1](https://user-images.githubusercontent.com/59403389/82733205-96036b00-9d12-11ea-97ca-294d6bf82a6e.jpg)

**Comment by Draze22** [comment]
Yet another reason to remove true form.

**Comment by dym-sh** [comment]
how is it **still** allowed to be skilled on lvl 1,
let alone automatically enabled on initial pick
is beyond me

**Comment by SanctusAnimus** [comment]
Should be fixed
