### ISSUE TITLE
Pinging abilities, modifiers and heroes

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [darklordabc/chc2issues#23]
You cant ping abilities on the duel section, abilities and modifiers on heroes on other teams, heroes up the top (in normal dota you can ping when theyre dead)

**Comment by Draze22** [comment]
At least some of these have been fixed (I'll come back and check which ones another time).

**Comment by Draze22** [comment]
Closing this since we have a new UI and therefor need an updated suggestion on this topic.
