### ISSUE TITLE
A number of improvements and fixes are needed.

### ISSUE THREAD

**Issue by Wintarogar** [darklordabc/chc2issues#230]
"Borrowed time" requires manual adjustment of the response, for example, at 25-50%. The current 400 hp are no good. Often, not only the players, but just creeps kill quickly, and it can’t even work.
Aeion disk - already noted that it is necessary to make a response from creeps, because this item is mainly for mages and they do not take damage from creeps very much, but if they are hit, you need a chance for survival, and not a useless item pve
I would like to increase the chance of losing the abilities of the hero, as well as reduce by 80% the chance of falling out of certain abilities once again, if the menu for selecting the ability was closed without a choice. Sometimes I spend 20 books, and the same garbage falls through 1-3 books.
The chance of falling neutral items is extremely small. Up to 70 waves can drop 4-5 pieces max per command.
Mistake - roshan, after time, can kill instantly through guardian angel.

**Comment by Wintarogar** [comment]
It is also necessary to allow the use of a multicast with aghanim's scepter on an ally within the radius of the fountain.

**Comment by darklordabc** [comment]
Multicast can now be cast on allies. Borrowed time is getting fixed. Netural items are being addressed in 2.0 update, as for ability chances, that probably wont change anytime soon sorry.

**Comment by Draze22** [comment]
I believe every issue here has no been addressed.
