### ISSUE TITLE
Alternate method of fixing spirit bear stats (other than letting it die).

### ISSUE THREAD

**Issue by ghosttttrick** [darklordabc/chc2issues#231]
It seems when you obtain vanguard before summoning the sipirit bear, the bear won't get status bonus unless you save the ability into a book and regain the ability.
Though this will need the player to transfer all items on bear to the hero, which is usually problematic(a lot of people lose all items on bear if they are careless)

**Comment by darklordabc** [comment]
Can you tell me steps on how to reproduce this bug? I tested with bear and it had normal stats bonuses from vanguard when it was in slot 1.

**Comment by ghosttttrick** [comment]
> Can you tell me steps on how to reproduce this bug? I tested with bear and it had normal stats bonuses from vanguard when it was in slot 1.

Mi lord,
I am sorry I mistaken how the bug was triggered, I tested twice and found that:

It seems when you obtain vanguard before summoning the sipirit bear, the bear won't get status bonus unless you save the ability into a book and regain the ability.
Even if you place the item on the ground and re-summon the bear and pick up the item, bear wont regain the stats bonus.

**Comment by Draze22** [comment]
This is no longer relevant since empty spell book got removed.
