### ISSUE TITLE
Yet another bug caused by a player loading in after randoming a hero.

### ISSUE THREAD

**Issue by Draze22** [darklordabc/chc2issues#234]
![image](https://user-images.githubusercontent.com/63279022/82816582-bb44d480-9ede-11ea-8a4a-7279aef22c55.png)
![image](https://user-images.githubusercontent.com/63279022/82816628-d57eb280-9ede-11ea-82ba-5f8b23bd7e90.png)

**Comment by SanctusAnimus** [comment]
should be fixed in next update
