### ISSUE TITLE
2 waveform charges talent doesn't work properly.

### ISSUE THREAD

**Issue by Draze22** [darklordabc/chc2issues#235]
![image](https://user-images.githubusercontent.com/63279022/83010536-bbb6aa00-a05b-11ea-8024-fab5e1b39780.png)

**Comment by SanctusAnimus** [comment]
Fixed in next update

**Comment by Draze22** [comment]
Does the fix work for all the talents that add charges to abilities (homing missile, disruption, etc)?

**Comment by SanctusAnimus** [comment]
should work for all of them
