### ISSUE TITLE
Second chance isn't working properly.

### ISSUE THREAD

**Issue by Draze22** [darklordabc/chc2issues#243]
Not sure if it's a visual problem where the buff icon that tells a player they have second chance doesn't disappear once it has been used or if second chance never activates.

![image](https://user-images.githubusercontent.com/63279022/83344345-bd78ba00-a348-11ea-8e13-53593459a923.png)
![image](https://user-images.githubusercontent.com/63279022/83344349-c6698b80-a348-11ea-9ab7-3cad7680a533.png)

**Comment by SanctusAnimus** [comment]
Can't reproduce

**Comment by Draze22** [comment]
This guy claims he lost his first aegis in a creep round, his second in a duel and never got to a third aegis from second chance.

![image](https://user-images.githubusercontent.com/63279022/85916000-a23d9380-b88f-11ea-8f6b-923fe081e4a2.png)
![image](https://user-images.githubusercontent.com/63279022/85916004-abc6fb80-b88f-11ea-85be-aaa680a1225a.png)

**Comment by SanctusAnimus** [comment]
Well i've tested this in and out in every possible case but couldn't get it to break, so any steps are appreciated

**Comment by Sheodar** [comment]
We didn't get report about this some time. There was a problem with duel & second chance. But it was fixed couple of days ago. Reopen this issue, if we'll get new reports about this.
