### ISSUE TITLE
Activating mana shield and then swapping it allows you to keep the mana shield buff.

### ISSUE THREAD

**Issue by Draze22** [darklordabc/chc2issues#245]
Pretty sure you lose the mana shield buff when you die but I'm not certain. Also I'm pretty sure their are other abilities that do similar things when swapped.

**Comment by SanctusAnimus** [comment]
Fixed

**Comment by Draze22** [comment]
Another example of something like this happening. I assume it will also get fixed in the next update but put it here just in case.

![image](https://user-images.githubusercontent.com/63279022/83482258-34e25100-a4e3-11ea-93e4-230a22e5255b.png)
![image](https://user-images.githubusercontent.com/63279022/83482279-3f9ce600-a4e3-11ea-8627-a9e7ca28d9f1.png)
