### ISSUE TITLE
Players getting banned ability combos in ffa and duos

### ISSUE THREAD

**Issue by Draze22** [darklordabc/chc2issues#249]
![image](https://user-images.githubusercontent.com/63279022/83481754-ee402700-a4e1-11ea-8f03-7922cb3ea992.png)
![image](https://user-images.githubusercontent.com/63279022/83481718-d1a3ef00-a4e1-11ea-9927-b9f8c44e8c2c.png)

**Comment by Draze22** [comment]
Another player getting the same banned combo.

![image](https://user-images.githubusercontent.com/63279022/83552270-d2be3600-a54c-11ea-8232-5a1e12044065.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/83717412-ffba3800-a675-11ea-82dc-74cce29ca706.png)
![image](https://user-images.githubusercontent.com/63279022/83717436-0fd21780-a676-11ea-9e9a-baaaa99cd370.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/84054822-4a7ddc00-a9f7-11ea-88cb-431747e3bbbb.png)

**Comment by SanctusAnimus** [comment]
Should be fixed in next update, leaving open until confirmed

**Comment by SanctusAnimus** [comment]
Noone reporting this now, i guess it's fixed now
