### ISSUE TITLE
Clicking the background in the hero selection screen can pick a hero.

### ISSUE THREAD

**Issue by Draze22** [darklordabc/chc2issues#250]
![image](https://user-images.githubusercontent.com/63279022/83506422-82be7f80-a50a-11ea-9d49-ce9f51c3b39f.png)

I haven't tested exactly how far from the hero you can click for it to still pick the hero but it is definitely further than the indicated border.

**Comment by Draze22** [comment]
Currently your mouse can be this far away from the hero and still select them.
![image](https://user-images.githubusercontent.com/63279022/87388035-4d1bb480-c5e7-11ea-81c8-878f1904fe8b.png)

**Comment by Draze22** [comment]
Your mouse can be roughly as far as the red dot and still select a hero.
![image](https://user-images.githubusercontent.com/63279022/87388431-227e2b80-c5e8-11ea-9c27-098eda1702c1.png)

**Comment by Sheodar** [comment]
U still should press on card. This area only for zoom card. But yeah, this area was reduced.
