### ISSUE TITLE
Neutral creeps don't attack wards (shadow shaman, venomancer)

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [darklordabc/chc2issues#26]

**Comment by Draze22** [comment]
I don't think this is much of an issue. Neutral creeps should only ever target these summons when there are no heroes to target. The only time this would ever happen is the brief period where players are reviving from one of their aegis'.

**Comment by AustraliaIsMyCity** [comment]
_Ghost scepter appears behind you and stabs you with ghost shroud_

**Comment by AustraliaIsMyCity** [comment]
_euls scepter laughs from the shadows_

**Comment by Draze22** [comment]
I suppose its up to darklord whether he thinks this needs to be fixed or not. But yeah it does not work the same as in regular Dota.

**Comment by Draze22** [comment]
This has been fixed.
