### ISSUE TITLE
The Golden Boy innate passive, doesn't make your bets 15% more valuable, it makes you bet 15% more

### ISSUE THREAD

**Issue by XAgent1990** [darklordabc/chc2issues#260]
This basicly increases the max bet from 50% to 57.5%
So if I have 1000 gold, and bet the 500 max, it acually bets 575 gold and also takes these away, so after the bet i am left with 425 gold.
I don't know if it effects the acual payout.

**Comment by Draze22** [comment]
This is virtually identical to issue #222 .
