### ISSUE TITLE
Summons don't get teleported with players

### ISSUE THREAD

**Issue by Draze22** [darklordabc/chc2issues#266]
The new update that forces players back into their arena if they try to leave also does the same thing to summons such as spirit bear. This causes spirit bear to stay in whichever arena it was initially summoned in. There do seem to be some exceptions where spirit bear does get moved to the duel arena.

![image](https://user-images.githubusercontent.com/63279022/84747247-5b7fac00-affa-11ea-8953-a55660a8f17f.png)
![image](https://user-images.githubusercontent.com/63279022/84747307-6f2b1280-affa-11ea-92fd-2f6243a16861.png)
![image](https://user-images.githubusercontent.com/63279022/84747342-7a7e3e00-affa-11ea-9d1c-12e3248a250c.png)
![image](https://user-images.githubusercontent.com/63279022/84747383-8407a600-affa-11ea-8b7a-6b30d2b0a08b.png)

**Comment by fcalife** [comment]
Fixed
