### ISSUE TITLE
Borrowed time improvement needed +aeon disk

### ISSUE THREAD

**Issue by Wintarogar** [darklordabc/chc2issues#268]
Ultimate simply does not have time to fire in the later stages of the game, what pve, what pvp.
It is necessary to manually set the trigger limit for pve / pvp
Improving aeon disk is also needed. His fix was, but the use at the hands of creeps never appeared

**Comment by darklordabc** [comment]
test

**Comment by Draze22** [comment]
Borrowed time is a very good skill and does not need to be buffed in my opinion.

The point about aeon disk being able to be triggered by creeps is however something I agree with and something that players seem to want.

**Comment by Draze22** [comment]
Both of these changes have been implemented.
