### ISSUE TITLE
You can sunder yourself

### ISSUE THREAD

**Issue by Draze22** [darklordabc/chc2issues#269]
This isn't a huge deal in general but does mean you can artificially take yourself from below the sunder threshold to above it without having another unit to sunder.

![image](https://user-images.githubusercontent.com/63279022/84887321-eafb8c80-b0d8-11ea-8e97-80c6ca8db0e0.png)
![image](https://user-images.githubusercontent.com/63279022/84887346-f18a0400-b0d8-11ea-9ad6-f2181b6023f4.png)

**Comment by SanctusAnimus** [comment]
Fixed
