### ISSUE TITLE
My Lich cannot call DRU's bear

### ISSUE THREAD

**Issue by Troy0604** [darklordabc/chc2issues#270]
My Lich cannot call DRU's bear
At first I can
but I'm not sure if I learned some siklls or bought some items, then my bear will disapper as soon as I call it when I do PVE. when I fight with players, I can call it.  Why?>?>??  Ｉ learn Lich's ultimate skill, dotes it related?

**Comment by Draze22** [comment]
Thank you for this report however this problem has already been addressed and the solution will be implemented with the next update.
