### ISSUE TITLE
The major version 2.0 bugs that need fixing ASAP

### ISSUE THREAD

**Issue by Draze22** [darklordabc/chc2issues#275]
The monkey creep wave is broken and doesn't end once all the creeps die some of the time.
![image](https://user-images.githubusercontent.com/63279022/85274650-92563600-b4c2-11ea-816a-cc86631914c5.png)
![image](https://user-images.githubusercontent.com/63279022/85274724-abf77d80-b4c2-11ea-9088-99e821ba31e0.png)
![image](https://user-images.githubusercontent.com/63279022/85274786-c2053e00-b4c2-11ea-9d2d-662786211656.png)

This bug can also happen on wave 20 (spider boss):
![image](https://user-images.githubusercontent.com/63279022/85274847-dba68580-b4c2-11ea-9865-a0e189a08b6f.png)
![image](https://user-images.githubusercontent.com/63279022/85274932-f678fa00-b4c2-11ea-917b-2a3621eee35f.png)

**Comment by Draze22** [comment]
Apparently the year beast becomes invulnerable at low hp.

![image](https://user-images.githubusercontent.com/63279022/85275057-258f6b80-b4c3-11ea-87bd-7b494c00600b.png)
![image](https://user-images.githubusercontent.com/63279022/85275087-2de7a680-b4c3-11ea-8b06-fcb991c1304b.png)

**Comment by fcalife** [comment]
On the last screenshot: the boss isn't immortal, its just not taking enough damage to actually die. Look at the arctic burn debuff and the boss's health regen, it reached an equilibrium where arctic burn isn't enough to overcome the regen anymore, due to the boss' health being low enough.

**Comment by Draze22** [comment]
All of these have been addressed on the dota2unofficial GutHub.
