### ISSUE TITLE
Most urgent changes to version 2.0

### ISSUE THREAD

**Issue by Draze22** [darklordabc/chc2issues#280]
1. Fix the bet slider.
![image](https://user-images.githubusercontent.com/63279022/85488060-00107800-b611-11ea-9c28-9270b9c8d548.png)
2. Allow manual input of bet amounts.
3. Give more time between rounds (20s should be good) and even more time for rounds with duels (25-30s should be good).
4. Finish implementing the ? preview feature as easier access to information/summaries of rounds has been highly requested.
5. Add a confirm button to the duel UI, especially since I don't have any clue what happens in the situation below.
![image](https://user-images.githubusercontent.com/63279022/85537222-1fca8f00-b657-11ea-9728-f16ab63fe2e3.png)

**Comment by fcalife** [comment]
Implemented
