### ISSUE TITLE
Creep balance regarding spell amp and health

### ISSUE THREAD

**Issue by Draze22** [darklordabc/chc2issues#283]
![image](https://user-images.githubusercontent.com/63279022/85540028-d891cd80-b659-11ea-94e3-f9b05f7b80af.png)

**Comment by fcalife** [comment]
creep health is extremely similar to 1.0's values, 50% seems like a massive upswing when those values server us for so long

**Comment by Draze22** [comment]
I found the values pretty good too.

**Comment by fcalife** [comment]
Creep damage was nerfed by ~10% on waves 21-50, spell damage was nerfed over the board. Health values stay the same.
