### ISSUE TITLE
Ancient creep health bars don't work well later in the game

### ISSUE THREAD

**Issue by Draze22** [darklordabc/chc2issues#285]
![image](https://user-images.githubusercontent.com/63279022/85796488-64e8e100-b77d-11ea-92fb-3ad09343b91a.png)

**Comment by fcalife** [comment]
Used to be that we could counteract this, but not anymore. You think just the crown would be enough (and removing the different health bar)?

**Comment by Draze22** [comment]
I think it will confuse some players initially but overall be worth it to have actually useful health bars for high hp creeps.

**Comment by fcalife** [comment]
Reverted
