### ISSUE TITLE
neutral items dont show up on the duel UI

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [darklordabc/chc2issues#29]

**Comment by Draze22** [comment]
It would definitely be nice to be able to see players neutral items when betting on them.

**Comment by dym-sh** [comment]
aghs, moonshard, and other perma-buffs should also be clearly indicated

**Comment by Draze22** [comment]
agreed

**Comment by SanctusAnimus** [comment]
Should be resolved with UI overhaul
