### ISSUE TITLE
Creep AI breaking

### ISSUE THREAD

**Issue by Draze22** [darklordabc/chc2issues#295]
![image](https://user-images.githubusercontent.com/63279022/86086379-f3929080-bae4-11ea-9305-f8000da6deb4.png)
![image](https://user-images.githubusercontent.com/63279022/86087399-7288c880-bae7-11ea-9b7e-fcbf40917c3f.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/86087791-65b8a480-bae8-11ea-9e0c-2cb0b7d254e6.png)
![image](https://user-images.githubusercontent.com/63279022/86087802-6e10df80-bae8-11ea-8dc0-e6ebc3cb42b6.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/86088219-39e9ee80-bae9-11ea-9d8f-244ce5b1e539.png)
![image](https://user-images.githubusercontent.com/63279022/86088234-4110fc80-bae9-11ea-87ed-365c41cb47bc.png)

**Comment by fcalife** [comment]
Fixed
