### ISSUE TITLE
astral spirit is sometimes invisible possibly only during undying ultimate

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [darklordabc/chc2issues#30]

**Comment by fcalife** [comment]
![image](https://user-images.githubusercontent.com/7921728/78852500-dcb33500-79f2-11ea-97db-c1464bad52d4.png)
unable to reproduce so far

**Comment by AustraliaIsMyCity** [comment]
> ![image](https://user-images.githubusercontent.com/7921728/78852500-dcb33500-79f2-11ea-97db-c1464bad52d4.png)
> unable to reproduce so far

only saw it once in a duel not sure what caused it but that was my best guess ill close this until i see it again
