### ISSUE TITLE
Player kept sproink after retraining untouchable

### ISSUE THREAD

**Issue by Draze22** [darklordabc/chc2issues#301]
![image](https://user-images.githubusercontent.com/63279022/86199504-a0304900-bb9d-11ea-9f2b-b5b49021c872.png)
![image](https://user-images.githubusercontent.com/63279022/86199543-b938fa00-bb9d-11ea-9a9a-8e8709122931.png)
![image](https://user-images.githubusercontent.com/63279022/86199553-c0600800-bb9d-11ea-80fb-79e2f022a301.png)

**Comment by SanctusAnimus** [comment]
Can't replicate
