### ISSUE TITLE
duel UI sometimes doesn't show all abilities.

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [darklordabc/chc2issues#31]
![image](https://user-images.githubusercontent.com/50186248/78619644-3582b080-78c1-11ea-8dbd-3e83639313ef.png)

**Comment by Draze22** [comment]
I had an opponent and only 4 of their 6 abilities were showing in the duel UI both before and during duels.

**Comment by Draze22** [comment]
Does this still happen with the new duel UI?

**Comment by SanctusAnimus** [comment]
duel ui ability count is hard capped iirc, anyway it should work fine
