### ISSUE TITLE
Totem can't be clicked on to view what it does.

### ISSUE THREAD

**Issue by Draze22** [darklordabc/chc2issues#316]
![image](https://user-images.githubusercontent.com/63279022/87236526-21090380-c42e-11ea-85ea-7cfa077c0b20.png)
![image](https://user-images.githubusercontent.com/63279022/87236528-28301180-c42e-11ea-9791-9ee5e9dbffe8.png)

**Comment by SanctusAnimus** [comment]
Totems will now show their abilities on hover too, so not a big deal (with next update)
