### ISSUE TITLE
Player lost a skill

### ISSUE THREAD

**Issue by Draze22** [darklordabc/chc2issues#321]
This gives very little indication of what caused the bug.
![image](https://user-images.githubusercontent.com/63279022/87493696-b9062780-c690-11ea-9746-84f71d4fb5a2.png)
![image](https://user-images.githubusercontent.com/63279022/87493632-8bb97980-c690-11ea-8f5b-e345347d9928.png)

**Comment by darklordabc** [comment]
@SanctusAnimus any clues what could have went wrong here, or safeguards we can add in?

**Comment by SanctusAnimus** [comment]
0 idea at all, initial ability giving doesn't influnce ability being hidden at all, all it can is toss it around, but even in 20th+ slot it still visible. I'll look into safeguarding if this bug report repeats, but current solution already has everything we can use to ensure clients will see ability update, there's nothing really we can add

**Comment by SanctusAnimus** [comment]
No more reports of it, closing for now
