### ISSUE TITLE
Crash at round 38 with crashlog 

### ISSUE THREAD

**Issue by Draze22** [darklordabc/chc2issues#337]
![image](https://user-images.githubusercontent.com/63279022/87865450-c553f280-c9b8-11ea-8c5e-18d25b844b44.png)
[crashloground_38.txt](https://github.com/darklordabc/chc2issues/files/4943129/crashloground_38.txt)

**Comment by SanctusAnimus** [comment]
Is the creep wave name known?

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/87867121-ff2ef400-c9cc-11ea-8063-e5e6476775bf.png)

**Comment by SanctusAnimus** [comment]
No longer reported, closing for now
