### ISSUE TITLE
Cooldown reduction isn't visually altering cooldowns properly

### ISSUE THREAD

**Issue by Draze22** [darklordabc/chc2issues#343]
![image](https://user-images.githubusercontent.com/63279022/87867582-ce04f280-c9d1-11ea-8fb4-693fee4d399b.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/87868752-ab2c0b80-c9dc-11ea-8b33-924284f75dd6.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/87869310-247a2d00-c9e2-11ea-8d63-941d3fd00149.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/87869319-3c51b100-c9e2-11ea-8259-7f51cb8770d5.png)

**Comment by darklordabc** [comment]
@SanctusAnimus can you investigate?

**Comment by SanctusAnimus** [comment]
> Cooldown reduction isn't visually altering cooldowns properly
Is that about cdr talents or fountain active reduction, reports above say about both, but can someone narrow issue a bit

**Comment by HappyFeedFriends** [comment]
This has already been fixed
