### ISSUE TITLE
Players are managing to get more than 6 abilities

### ISSUE THREAD

**Issue by Draze22** [darklordabc/chc2issues#349]
![image](https://user-images.githubusercontent.com/63279022/88130753-ad7da800-cc1e-11ea-9be8-946bca033ef2.png)
![image](https://user-images.githubusercontent.com/63279022/88130511-1dd7f980-cc1e-11ea-98df-e39d908d2bc0.png)
![image](https://user-images.githubusercontent.com/63279022/88130526-25979e00-cc1e-11ea-8071-809efda6fc5a.png)
![image](https://user-images.githubusercontent.com/63279022/88130569-3fd17c00-cc1e-11ea-94d1-d94752f6a76a.png)
![image](https://user-images.githubusercontent.com/63279022/88130581-45c75d00-cc1e-11ea-9068-15382ee46444.png)

**Comment by SanctusAnimus** [comment]
Fixed
