### ISSUE TITLE
Timber spider round has no name and instead displays "round_timber_spider"

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [darklordabc/chc2issues#37]
![image](https://user-images.githubusercontent.com/50186248/78635405-7bec0580-78e9-11ea-8a5f-22608ac8d066.png)

**Comment by Blasphemy-Incarnate** [comment]
Should be able to quickly patch this by adding "npc_dota_timber_spider" "Timber Spider" to addon_english.txt. Can't really test this on my end though.

**Comment by SanctusAnimus** [comment]
Added to localization
