### ISSUE TITLE
Using blink dagger, aether lens and high cast range talents (~250 side ~375 up) you can enter other players arenas and kill them

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [darklordabc/chc2issues#40]

**Comment by fcalife** [comment]
should be fixed next version (next upload)

**Comment by AustraliaIsMyCity** [comment]
blink [AM, QOP] + aether lens + seer stone + cast range talents (not all needed) allows players to enter other players arenas

**Comment by fcalife** [comment]
do you have the rough threshold at which it becomes possible?

**Comment by AustraliaIsMyCity** [comment]
seems to be about 1500-1600 units

**Comment by fcalife** [comment]
thanks
