### ISSUE TITLE
Using supernova in the fountain lets people attack you and after you die you can still be attacked until you enter and leave a creep round

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [darklordabc/chc2issues#41]
Also consumed aegises

**Comment by darklordabc** [comment]
@Draze22 is this still an issue?

**Comment by Draze22** [comment]
Supernova currently isn't in the game so not an issue unless it gets added back in.

**Comment by Draze22** [comment]
@darklordabc this brings up the question of whether you want to ever add back any abilities that have been removed after the devs have had a chance to rework/fix them.
