### ISSUE TITLE
The swarm (weaver) isnt affected by crown of the dominator

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [darklordabc/chc2issues#42]
idk it seems like a summon

**Comment by SanctusAnimus** [comment]
But it's not a real summon? You can't control swarmlings in any way, count them just as special effect. Or you count grimstroke 2nd ability spirit that silences also as summon?

**Comment by Draze22** [comment]
Wraith king skeletons also can't be controlled but are considered skeletons only when they respawn.

**Comment by SanctusAnimus** [comment]
They are not considered as summons initially only because they don't have owner or any pointers to WK on initial spawn for Valve reasons. And also, damage of WK skeletons is increased from auras like Vlads, but swarmlings damage is not, isn't it?
