### ISSUE TITLE
static link + multicast can target summoned creeps

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [darklordabc/chc2issues#50]

**Comment by Draze22** [comment]
Actually static link + multicast was targeting neutral creeps.

**Comment by AustraliaIsMyCity** [comment]
> Actually static link + multicast was targeting neutral creeps.
Well yes it'll do that if you use bugs to enter other peoples arenas but that doesnt matter because you arent supposed to be able to. What does matter is being able to use it on summons because you are supposed to encounter those while playing the game normally

**Comment by SanctusAnimus** [comment]
Static Link disabled from multicast from next update
