### ISSUE TITLE
Game timer sometimes freezes stopping the next round from starting.

### ISSUE THREAD

**Issue by Draze22** [darklordabc/chc2issues#52]
Only 2 times I've seen it stop were both at 19 seconds.
![image](https://user-images.githubusercontent.com/63279022/78699743-b97f7b80-7947-11ea-9b0a-3df2d459c13c.png)

**Comment by mmdts** [comment]
Happened in match ID 5341366941 as well... right after DK disconnected, not sure if that's related.

**Comment by mmdts** [comment]
Match ID 5341373022, freezes randomly when timer is 36

**Comment by darklordabc** [comment]
This is worst bug, can anyone find what is causing it?

**Comment by fcalife** [comment]
Should be fixed after the latest update

**Comment by AustraliaIsMyCity** [comment]
https://cdn.discordapp.com/attachments/694440472273354762/698487748616781834/message.txt
https://cdn.discordapp.com/attachments/694440472273354762/698487214065188864/20200411205602_1.jpg

**Comment by Draze22** [comment]
Haven't had any reports on this in a while so I'll close this for now.
