### ISSUE TITLE
Swapping an ability with partner then moving its hotkeys duplicates it

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [darklordabc/chc2issues#58]
![image](https://user-images.githubusercontent.com/50186248/78853397-21c28000-7a62-11ea-9488-26e1977dbc36.png)
![image](https://user-images.githubusercontent.com/50186248/78853431-343cb980-7a62-11ea-8099-fa8aa857f9db.png)
The duplicated ability disappears after a round or so but thats enough time to dupe it for a duel

**Comment by AustraliaIsMyCity** [comment]
sh*t theyre the same hero in the screenshots well anyways it does work

**Comment by Draze22** [comment]
Urgent Update!: You can retrain the duplicated ability to permanently have an extra ability.

**Comment by SanctusAnimus** [comment]
Fixed
