### ISSUE TITLE
Abilities disappearing

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [darklordabc/chc2issues#59]
![image](https://user-images.githubusercontent.com/50186248/78855301-da8abe00-7a66-11ea-827a-deda9643d21f.png)
initially skywrath had torrent disappear for him (all other abilities were still there) and for me all his abilities disappeared (although 2 have no reappeared) according to other people they can see 4 of his abilities.
![image](https://user-images.githubusercontent.com/50186248/78855795-3efa4d00-7a68-11ea-9f89-5b507790c240.png)

**Comment by darklordabc** [comment]
Can you confirm if this is still happening. We uploaded something that was meant to fix this.

**Comment by AustraliaIsMyCity** [comment]
only seen once ill reopen if it happens again
