### ISSUE TITLE
Wraith King's Reincarnation

### ISSUE THREAD

**Issue by beepbeepboop** [darklordabc/chc2issues#6]
Scepter doesn't work at all, haven't tested it while play wraith king, but getting scepter reincarnation in duo means your teammate does not become a wraith like he should.

Reincarnation also doesn't work correctly in duo duels, if you die, you start to reincarnate but then as you reincarnate if your teammate dies the duel is over

**Comment by Draze22** [comment]
Half of the issue here is a duplicate and the other half is now a tooltip.
