### ISSUE TITLE
[Suggestion] Double-Down/All-In Mechanic

### ISSUE THREAD

**Issue by Blasphemy-Incarnate** [darklordabc/chc2issues#62]
**Concept**
The concept for this mechanic is an extension of the current betting system. It aims to create a sense of excitement with a high risk/high reward style gamble. At the moment you cannot bet more than 50% of your wealth, with this system you could potentially -- as the name implies -- go all in for an extra risky bet. I want to encourage nail-biting moments with extremely risky bets on both teams, teams watching as the duel progresses.

[Concept Visualisation](https://imgur.com/DoXzAFm)
[Tokens Visualisation](https://imgur.com/bHcjE4k)

**Tokens**
A 'token' is required to place this unique bet, these tokens could be given out at the start of a game, at certain rounds, or earned in some way. The tokens prevent this bet from overruling the standard bet, a player must consider the most opportune time to risk it, as tokens are limited.
[Ideas](https://imgur.com/WSRZwmt)

**Betting**
The betting could be a standalone bet made in parallel with the standard bet, it could be a toggle to 'double down', or it could be an 'all in' button that puts all you have on the line.
[Ideas](https://imgur.com/xXa1JjQ)

**Winnings/Losings**
Due to the limited nature of this bet, more than just money could be on the line. Perhaps winning this bet nets a Retraining item? Maybe even a permanent or temporary buff? However, to compensate for these potential riches, there must be a punishment for incorrectly or flippantly betting.
[Ideas (Winnings)](https://imgur.com/WPY0LGm), [Ideas (Losings)](https://imgur.com/9K4eFCE)

These ideas could be mismatched, discarded, or swapped around to find the most enjoyable and balanced version.

Foreseeable issues: Disadvantages low net-worth teams (the opposite of what was intended), further encourages throwing duels (subjective issue, should be fine if the duelling teams can't see bets).

**Comment by mmdts** [comment]
With nothing preventing people from throwing duels just to spite others (happens fairly often), I can't see myself supporting this.

People (not me, but many others) already quit the game when they lose 5K in an all-in bet on someone that loses fairly, let alone throws. Can't imagine if they lost the full 10K.

I can imagine vanilla CHC's past betting system to have allowed you to bet more than half your gold when the game was still starting out and got changed to this current system to avoid such situations, though I can't really be sure.

**Comment by Blasphemy-Incarnate** [comment]
> 
> 
> With nothing preventing people from throwing duels just to spite others (happens fairly often), I can't see myself supporting this.
> 
> People (not me, but many others) already quit the game when they lose 5K in an all-in bet on someone that loses fairly, let alone throws. Can't imagine if they lost the full 10K.
> 
> I can imagine vanilla CHC's past betting system to have allowed you to bet more than half your gold when the game was still starting out and got changed to this current system to avoid such situations, though I can't really be sure.

Obviously the duelers shouldn't be allowed to see these bets. They can still choose to throw at the risk of losing themselves gold and potentially letting someone get a win on their all-in bet, but it's risky for them too.

I know that some people will choose to make a huge bet and leave if they lose it, and while I don't like having to tailor a game's design towards these people, I do understand that it's an inevitability that can't be avoided.

With this in mind, I did offer other alternatives to the 'all-in' version. The mechanic could purely use tokens and not require any extra gold to be spent, the negative from losing it also doesn't have to be monetary. This still leaves room for abandoners, but that's why this is just a suggestion, it can be tweaked and changed until it can entertain both parties. Although it is a glaring issue, I believe it can be worked around.

**Comment by Draze22** [comment]
I feel like with the new innates that affect betting and gold from winning, jackpots, etc, this is too complicated to implement.

**Comment by fcalife** [comment]
This is now in the game, in a certain way, with the Gambler innate
