### ISSUE TITLE
Upcoming Duels

### ISSUE THREAD

**Issue by Blasphemy-Incarnate** [darklordabc/chc2issues#63]
After a duel finishes, a sidebar (or something else) could **display which teams will be in the next duel and when it will take place**. This would nullify the nasty surprise of *"I just need one more round to prepare, I hope I'm not in a duel now. Oh damnit."*. I personally think this allows for both teams to ready themselves and draft/purchase accordingly.

If that's too much of an advantage and/or the surprise is considered better, displaying said information could be delayed until a certain number of rounds before the duel.

**Comment by fcalife** [comment]
nice idea

**Comment by darklordabc** [comment]
After a duel finishes, isnt there usually another duel straight away? So why do you need a notification of who is dueling next? Wouldnt you need to say who is dueling next when you announce the current duel?

**Comment by Draze22** [comment]
There's only another duel immediately if all the players are still alive. Once you get down to a few players/teams it can be 5 rounds between duels.

**Comment by Blasphemy-Incarnate** [comment]
> 
> 
> After a duel finishes, isnt there usually another duel straight away? So why do you need a notification of who is dueling next? Wouldnt you need to say who is dueling next when you announce the current duel?

I also made this suggestion (in discord) before that change was implemented iirc.
