### ISSUE TITLE
Title up the top only shows last two words of players' names

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [darklordabc/chc2issues#64]
![image](https://user-images.githubusercontent.com/50186248/78866699-3e22e480-7a83-11ea-921b-b92f381b1a9b.png)
Mine (Terrorblade) should be 'Australia is my city'
SF's should be 'Small Dick Big Dreams'
They are shortened to the last 2 words

**Comment by fcalife** [comment]
Would you rather only have the last 2 words, or have the names horribly squished to the point of unreadability?

I think this is a good compromise

**Comment by Draze22** [comment]
Could we have the first 2 words instead of the last 2 maybe?

**Comment by darklordabc** [comment]
Yes it should have the first 2 words, not last two words.

**Comment by Draze22** [comment]
Not a problem with the new UI.
