### ISSUE TITLE
Dead players can purchase and drop tomes from stash which alive players can pick up and use.

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [darklordabc/chc2issues#67]

**Comment by darklordabc** [comment]
Is this still and issue, I just tested and when I died I had no money
![image](https://user-images.githubusercontent.com/16277198/79034039-6bdc6a80-7bf6-11ea-8473-ff82c56f6c61.png)

**Comment by AustraliaIsMyCity** [comment]
After you die you can still gain money from selling neutral items (which is another bug and i guess if thats fixed this will too)
