### ISSUE TITLE
Rearm + Blur

### ISSUE THREAD

**Issue by Draze22** [darklordabc/chc2issues#68]
Rearm + blur can be used to be unkillable in creep rounds. Not sure if you want this to be in the game or not.

**Comment by fcalife** [comment]
Rearm will be reworked to something similar to its OAA version

**Comment by Draze22** [comment]
Does rearm in OAA reduce cooldowns by a set amount? If so blur + rearm will likely still be a problem as it has a 9 second cooldown with aghs + octarine.

**Comment by fcalife** [comment]
It works like this game's fountain effect, making your cooldowns go faster by a set rate while you channel. If some skills are still problematic after that, we can just increase their cooldown.

**Comment by Draze22** [comment]
Sounds good.
