### ISSUE TITLE
Entering a creep round or duel cancels all queued actions.

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [darklordabc/chc2issues#69]
When entering a duel if you try to preemptively blink to the other side of the arena for example, the action is queued up but upon entering the duel it isnt fulfilled.

**Comment by SanctusAnimus** [comment]
This is intended mechanic

**Comment by AustraliaIsMyCity** [comment]
> This is intended mechanic
Makes it kinda awkward but ok
