### ISSUE TITLE
Replica racketee splash doesnt work with fury swipes

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [darklordabc/chc2issues#70]

**Comment by darklordabc** [comment]
What do you mean? Its not meant to apply fury swipes?

**Comment by AustraliaIsMyCity** [comment]
> What do you mean? Its not meant to apply fury swipes?

It doesnt splash off the fury swipes damage like battlefury does

**Comment by darklordabc** [comment]
This is an old reddit article, but can you find a link that says battlefury and fury swipes stacks? https://www.reddit.com/r/DotA2/comments/2b3y6r/how_does_battle_fury_interact_with_fury_swipes/

**Comment by Draze22** [comment]
What AustraliaIsMyCity means is you can cleave of the bonus damage provided fury swipes with battlefury, great cleave, etc. This is similar to being able to crit or lifesteal off the bonus damage provided by fury swipes.

**Comment by Draze22** [comment]
I would also be interested to know if elder dragon form splash damage is affected by fury swipes damage.

**Comment by darklordabc** [comment]
Are you sure battle fury works with fury swipes, the link I posted above says it doesn't increase the damage from battlefury.

**Comment by AustraliaIsMyCity** [comment]
it 100% does

**Comment by AustraliaIsMyCity** [comment]
![image](https://user-images.githubusercontent.com/50186248/79035281-47858b80-7c00-11ea-9cfa-7b3a5ab37caa.png)
after 2 hits
![image](https://user-images.githubusercontent.com/50186248/79035283-50765d00-7c00-11ea-8d07-efaa26fc7d44.png)
after a bunch more hits

**Comment by Draze22** [comment]
The reason that post from 5 years ago isn't accurate is they changed how cleave works around 2 years ago (from memory).

**Comment by Sheodar** [comment]
Now Replica Rackatee work with fury swipes (like battle fury)
