### ISSUE TITLE
Rearm levels up at 6,21,36 instead of 6,12,18

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [darklordabc/chc2issues#74]
6,21,36
![image](https://user-images.githubusercontent.com/50186248/78889765-ac799e00-7aa7-11ea-8853-4523af2d900b.png)
![image](https://user-images.githubusercontent.com/50186248/78889779-b13e5200-7aa7-11ea-925d-b09d49051838.png)

**Comment by beepbeepboop** [comment]
This is not a bug but a balance, it used to be level 3 rearm at level 31 and they recently nerfed it to level 36 because rearm is too OP

**Comment by darklordabc** [comment]
We should at least add text explaining this difference
