### ISSUE TITLE
Neutral item tooltip displays double actual sell price

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [darklordabc/chc2issues#76]
![image](https://user-images.githubusercontent.com/50186248/78956480-c8bc2000-7b25-11ea-94b4-f512d19a655b.png)
![image](https://user-images.githubusercontent.com/50186248/78956484-ce196a80-7b25-11ea-9402-5bf07864e2ec.png)

**Comment by darklordabc** [comment]
Fixed, thanks for the report
