### ISSUE TITLE
Loser curse says that it works in duels but actually doesnt

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [darklordabc/chc2issues#79]
![image](https://user-images.githubusercontent.com/50186248/78962100-ee055a00-7b36-11ea-97bd-912d8c5aa09d.png)
bruh moment

**Comment by fcalife** [comment]
uhhh, my bad, it doesn't
![image](https://user-images.githubusercontent.com/7921728/78962219-45211580-7aca-11ea-89f4-8ce51defe0c8.png)
doubleBruh

**Comment by darklordabc** [comment]
Okay, can we hide the loser debuff while the player is in a duel, so there is no confusion?

**Comment by fcalife** [comment]
> an we hide the loser debuff while the player is in a duel, so there is no confusion?

Added
