### ISSUE TITLE
Update tooltips for abilties that are known bugs / balanced

### ISSUE THREAD

**Issue by beepbeepboop** [darklordabc/chc2issues#82]
Just like how chakram says "not removable" and io spirits says "aghs not work"
I really like these. But only half the abilities have updated tooltips
You could write:
"battlefury not work" on TrueForm  (apparently when exiting True Form battlefury does work now)
"aghs not work" on Reincanation
"roshan is immune" on Earth Splitter

I only know all these things because I've chosen the skill and found out the hard way after buying an aghs and it doesnt work. But if you updated the tooltips then new players would be less confused. And you'd get less people on the discord complaining about known bugs

**Comment by darklordabc** [comment]
I'd rather fix the bug when write text about the bug. This would require some work in translating to chinese and Russian. Is there some examples of texts we should add to abilities that are not bugs we are going to fix later?

**Comment by Draze22** [comment]
We could label every ability that isn't affected by spell amp.

**Comment by Draze22** [comment]
We could also use a tooltip on every ability that can't be multicast or rearmed.
The rearm tooltip could be skipped if rearm is being remade soon. 
It makes more sense to make the tooltip for each ability rather than for multicast and rearm otherwise the tooltip for them will be insanely long.

**Comment by Draze22** [comment]
Should we make a megathread for tooltip errors/suggestions.

**Comment by Draze22** [comment]
This can now be closed. There was a new issue opened for tooltip suggestions.
