### ISSUE TITLE
If timer is extended the gold bounty icon appears above duelers heads too early

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [darklordabc/chc2issues#85]
![image](https://user-images.githubusercontent.com/50186248/79033567-80b6ff00-7bf2-11ea-8ba7-50be5d62e2c6.png)

**Comment by darklordabc** [comment]
This appears when you confirm your bet, nothing about the timer

**Comment by AustraliaIsMyCity** [comment]
> This appears when you confirm your bet, nothing about the timer

oh so thats what it does i didnt really understand what it meant
