### ISSUE TITLE
Add cheat mode testing commands to make bug finding easier 

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [darklordabc/chc2issues#89]
Also lets people try out cool builds

Commands needed
-sethero [hero] # sets your hero to a specific hero
-learnability # lets you learn a new ability from the list of all abilities and adds it to the last slot available
-removeability # lets you click an ability to remove it from your hero
-setround [round number] # sets the round to given number
-rosh # next round will be a roshan

Comment any other ideas for commands :)

**Comment by Blasphemy-Incarnate** [comment]
> -learnability # lets you learn a new ability from the list of all abilities and adds it to the last slot available
Alternatively -item'ing a spell scroll with meta-data? Not sure how you went about storing information in them (are they unique items or is the ability just cached somewhere), but it might be easier to add the ability to cheat in one with an ability stored.

**Comment by AustraliaIsMyCity** [comment]
> > -learnability # lets you learn a new ability from the list of all abilities and adds it to the last slot available
> 
> Alternatively, -item'ing a spell scroll with meta-data? Not sure how you went about storing information in them (are they unique items or is the ability just cached somewhere), but it might be easier to add the ability to cheat in one with an ability stored.

seems over complicated

**Comment by SanctusAnimus** [comment]
maybe i could enable some of our debugging commands for the cheat mode, i'll need to look closer

**Comment by avfanclub** [comment]
what about command to (temporary) stop counting (and also continue) time to next wave?

**Comment by knightfeng** [comment]
This would be very helpful.

**Comment by Draze22** [comment]
We got this finally!
