### ISSUE TITLE
I would like abilities to refresh both before and after a duel.

### ISSUE THREAD

**Issue by Draze22** [darklordabc/chc2issues#90]
At the moment it feels super annoying to use a long cooldown abilities during a neutral round and not have it ready for a duel. Refreshing all abilities before and after a duel would make duels feel more fair as everyone would be fighting at their full power every duel.

I would suggest asking this in announcements so everyone can vote on if they want this change.

**Comment by darklordabc** [comment]
I don't think we are going to do this. This would remove the tactical of choice of deciding to use an ult to survive a creep round or saving it for a duel.

**Comment by Draze22** [comment]
At the moment you have no idea when you are going to be in a duel so Its less of a tactical decision and more you hope like hell you don't get in a duel when your abilities are on cooldown.

**Comment by dym-sh** [comment]
imo, until we have proper tournament rules for who duels when, all abilities and items should just reset after every round and be uncastable between rounds, since self-targeted things already can't be used during that time
