### ISSUE TITLE
Add a tome of [agi/int/str] for 2k-5k gold that gives +0.5 stat growth per level

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [darklordabc/chc2issues#92]
Would make the ultra late game pretty interesting
Rounds until its as worth to buy as a regular tome:
2k | 12 
3k | 18
4k | 24
5k | 30

**Comment by fcalife** [comment]
isn't that just a round-based discount on tomes?

**Comment by AustraliaIsMyCity** [comment]
Its an alternative to tome with a short term loss for a long term game idk might make it a bit more interesting and strategic when buying tomes

**Comment by Draze22** [comment]
Anyone still interested in adding this?
