### ISSUE TITLE
Spell amp + percentage-based damage rework proposal

### ISSUE THREAD

**Issue by fcalife** [darklordabc/chc2issues#94]
Key points:
 * All percentage damage spells will have their numbers buffed, but no longer be affected by spell amplification **at all**.
 * Spell amplification gained from intelligence is reverted to vanilla dota values (basically nothing). Currently it is equal to 0.6% per point of int.
 * Heroes will gain a spell amp buff when fighting a creep round (but not a duel), equal to 1% spell amp per point of intelligence above 50.
 * The value above is increased to 1.4%/1.8% if you purchase Sky Staff / Starforce.
 * Sky Staff and Starforce keep their current stats, with a small reduction in their flat spell amp bonus (which will work on duels).

---

Ключевые моменты:

* Все заклинания, наносящие урон в процентах, будут иметь свои баффы, но больше не будут подвержены усилению заклинаний.
* Усиление заклинаний, полученное от интеллекта, возвращается к ванильным значениям доты (практически ничего). В настоящее время он равен 0,6% за точку Int.
* Герои получают усиление заклинаний при борьбе с раундом крипа (но не дуэлью), равное 1% усиления заклинаний на единицу интеллекта выше 50.
* Значение выше увеличено до 1,4% / 1,8%, если вы покупаете Sky Staff / Starforce.
* Sky Staff и Starforce сохраняют свою текущую статистику, с небольшим уменьшением бонуса от плоского усилителя заклинаний (который будет работать на дуэлях).

**Comment by Draze22** [comment]
This is outdated since we have a new spell amp rework proposal (#263 ).
