### ISSUE TITLE
ice-trap-caster creep's spells nearly invisible on on the ice tiles

### ISSUE THREAD

**Issue by dym-sh** [darklordabc/chc2issues#95]
ice-trap-caster creep's spells nearly invisible on on the ice tiles
the original mod had all ice-tiles converted to desert like a month ago,
but i much rather color of the trap be changed to red+black, so it would always be visible on every other future terrain

**Comment by AustraliaIsMyCity** [comment]
separated bug to its own thread

**Comment by dym-sh** [comment]
bonus bug: traps entirely covered by things like viper's AOE-poison

**Comment by fcalife** [comment]
Changed the ice arenas to the new TI10 terrain.

This change is in the 2.0 branch.
