### ISSUE TITLE
Queen of Pain's lvl 25 scream of pain fear talent doesn't work on creeps.

### ISSUE THREAD

**Issue by Draze22** [darklordabc/chc2issues#97]
In regular Dota scream of pain sends enemy creeps towards base and stuns neutral creeps. Don't know what it does in CHC but General Miau claimed it didn't work. (can someone add the needs confirmation label).

**Comment by AustraliaIsMyCity** [comment]
Personally I've used this and seen it work so I'm quite sceptical

**Comment by Draze22** [comment]
If that's the case this can be closed.
