### ISSUE TITLE
Remove/change Skywrath Mage's lvl 20 talent 'global concussive shot' makes concussive shot useless.

### ISSUE THREAD

**Issue by Draze22** [darklordabc/chc2issues#99]
Quite rare that this will affect someone but if a player gets concussive shot on Skywrath Mage, hitting level 30 auto levels the lvl 20 talent 'global concussive shot' making concussive shot useless for neutral rounds.

**Comment by AustraliaIsMyCity** [comment]
This evokes the question of should all useless talents (eg. for removed abilities like wukongs) be removed and replaced by others?

**Comment by Draze22** [comment]
I added this problem to another bigger thread.

**Comment by AustraliaIsMyCity** [comment]
you saw nothing

**Comment by Draze22** [comment]
;)
